/* eslint-disable react-refresh/only-export-components */

import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "ruche-language";
const SUPPORTED_LANGUAGES = ["fr", "en", "nl"];
const DEFAULT_LANGUAGE = "fr";

const DATE_LOCALES = {
  fr: "fr-BE",
  en: "en-GB",
  nl: "nl-BE",
};

const USER_ROLES = [
  "Délégué PECA",
  "Délégué au Contrat d'Objectifs",
  "Direction",
  "Enseignant",
  "Educateur",
  "Membre d'un CPMS",
  "Futur enseignant",
  "Intervenant culturel",
  "Etudiant en Ecole Superieure des Arts",
  "Référent culturel",
  "Référent scolaire",
  "Autre",
];

const ROLE_LABELS = {
  fr: {
    "Délégué PECA": "Délégué PECA",
    "Délégué au Contrat d'Objectifs": "Délégué au Contrat d'Objectifs",
    Direction: "Direction",
    Enseignant: "Enseignant",
    Educateur: "Educateur",
    "Membre d'un CPMS": "Membre d'un CPMS",
    "Futur enseignant": "Futur enseignant",
    "Intervenant culturel": "Intervenant culturel",
    "Etudiant en Ecole Superieure des Arts":
      "Etudiant en Ecole Superieure des Arts",
    "Référent culturel": "Référent culturel",
    "Référent scolaire": "Référent scolaire",
    Autre: "Autre",
  },
  en: {
    "Délégué PECA": "PECA representative",
    "Délégué au Contrat d'Objectifs": "Objectives Contract delegate",
    Direction: "School leadership",
    Enseignant: "Teacher",
    Educateur: "Educator",
    "Membre d'un CPMS": "CPMS member",
    "Futur enseignant": "Future teacher",
    "Intervenant culturel": "Cultural practitioner",
    "Etudiant en Ecole Superieure des Arts": "Arts college student",
    "Référent culturel": "Cultural coordinator",
    "Référent scolaire": "School coordinator",
    Autre: "Other",
  },
  nl: {
    "Délégué PECA": "PECA-afgevaardigde",
    "Délégué au Contrat d'Objectifs":
      "Afgevaardigde van het doelstellingencontract",
    Direction: "Directie",
    Enseignant: "Leerkracht",
    Educateur: "Opvoeder",
    "Membre d'un CPMS": "Lid van een CLB",
    "Futur enseignant": "Toekomstige leerkracht",
    "Intervenant culturel": "Cultureel begeleider",
    "Etudiant en Ecole Superieure des Arts": "Student aan een kunsthogeschool",
    "Référent culturel": "Cultureel referentiepersoon",
    "Référent scolaire": "Schoolreferentiepersoon",
    Autre: "Andere",
  },
};

const CARD_CATEGORIES = {
  fr: [
    { key: "domaine", label: "Domaines d'expression culturelle et artistique" },
    {
      key: "conditions-enseignant",
      label: "Conditions pour l'enseignant/intervenant",
    },
    {
      key: "recommandations-enseignant",
      label: "Recommandations pour l'enseignant/intervenant",
    },
    { key: "visees", label: "Visées & effets pour les élèves" },
    { key: "conditions-equipe", label: "Conditions pour l'équipe éducative" },
    {
      key: "recommandations-equipe",
      label: "Recommandations pour l'équipe éducative",
    },
    { key: "free", label: "À vous de jouer !" },
  ],
  en: [
    { key: "domaine", label: "Cultural and artistic expression domains" },
    {
      key: "conditions-enseignant",
      label: "Conditions for teachers/practitioners",
    },
    {
      key: "recommandations-enseignant",
      label: "Recommendations for teachers/practitioners",
    },
    { key: "visees", label: "Aims & impacts for students" },
    { key: "conditions-equipe", label: "Conditions for the educational team" },
    {
      key: "recommandations-equipe",
      label: "Recommendations for the educational team",
    },
    { key: "free", label: "Your turn!" },
  ],
  nl: [
    { key: "domaine", label: "Domeinen van culturele en artistieke expressie" },
    {
      key: "conditions-enseignant",
      label: "Voorwaarden voor leerkrachten/begeleiders",
    },
    {
      key: "recommandations-enseignant",
      label: "Aanbevelingen voor leerkrachten/begeleiders",
    },
    { key: "visees", label: "Doelen & effecten voor leerlingen" },
    { key: "conditions-equipe", label: "Voorwaarden voor het schoolteam" },
    {
      key: "recommandations-equipe",
      label: "Aanbevelingen voor het schoolteam",
    },
    { key: "free", label: "Jij bent aan zet!" },
  ],
};

const messages = {
  fr: {
    common: {
      loading: "Chargement...",
      close: "Fermer",
      cancel: "Annuler",
      save: "Enregistrer",
      edit: "Modifier",
      delete: "Supprimer",
      confirm: "Confirmer",
      page: "Page",
      previous: "Précédent",
      next: "Suivant",
      unknownUser: "Utilisateur inconnu",
      yes: "Oui",
      no: "Non",
    },
    language: {
      label: "Langue",
      fr: "Français",
      en: "English",
      nl: "Nederlands",
    },
    header: {
      profile: "Profil",
      inbox: "Boîte de réception",
      admin: "Admin",
      logout: "Déconnexion",
      login: "Connexion",
      register: "Créer un compte",
    },
    landing: {
      title: "Bienvenue dans La Ruche",
      loading: "Chargement de votre session...",
      connected: "Continuez votre activité en quelques clics.",
      guest: "Connectez-vous ou créez votre compte pour commencer.",
      goProfile: "Accéder au profil",
      createHive: "Créer une Ruche",
      learnMore: "En savoir plus",
      signIn: "Se connecter",
      createAccount: "Créer un compte",
      tutorial: "Tutoriel",
      tutorialPlaceholder: "Contenu du tutoriel à venir...",
      gdpr: "RGPD / Confidentialité",
      gdprPlaceholder: "Informations de confidentialité à venir...",
      wip: "En cours de développement",
      wipPlaceholder: "Prochaines étapes prévues à venir...",
    },
    login: {
      title: "Connexion",
      identifier: "Nom d'utilisateur ou email",
      password: "Mot de passe",
      submit: "Se connecter",
      submitting: "Connexion...",
      forgot: "Mot de passe oublié ?",
      noAccount: "Pas encore de compte ?",
      register: "Inscription",
    },
    register: {
      title: "Créer un compte",
      username: "Nom d'utilisateur (unique)",
      email: "Email",
      firstName: "Prénom",
      lastName: "Nom",
      role: "Rôle",
      roleOther: "Précisez votre rôle",
      password: "Mot de passe",
      passwordConfirm: "Confirmation du mot de passe",
      submit: "Créer mon compte",
      submitting: "Création...",
    },
    forgotPassword: {
      title: "Mot de passe oublié",
      email: "Email",
      submit: "Envoyer le lien",
    },
    resetPassword: {
      invalidLink: "Lien invalide",
      title: "Nouveau mot de passe",
      password: "Mot de passe",
      passwordConfirm: "Confirmer le mot de passe",
      submit: "Mettre à jour",
    },
    protectedRoute: {
      loading: "Chargement...",
    },
    profile: {
      title: "Mon profil",
      hivesTab: "Mes ruches",
      settingsTab: "Modifier mon profil",
      username: "Nom d'utilisateur",
      email: "Email",
      role: "Rôle",
      createNewHive: "Créer une nouvelle Ruche",
      modalselectHiveTypeTitle: "Type de ruche",
      selectHiveTypeMessage: "Quel type de ruche voulez-vous créer ?",
      selectStandardHive: "Ruche standard",
      selectDcoHive: "Ruche DCO",
      myHives: "Mes Ruches",
      sharedHives: "Ruches partagées",
      createdAt: "Créée le",
      updatedAt: "Dernière édition",
      open: "Ouvrir",
      duplicate: "Dupliquer",
      duplicating: "Duplication...",
      deleteProfileTitle: "Supprimer mon profil",
      deleteProfileDesc:
        "Cette action est irréversible et supprimera vos données.",
      confirmDeletion: "Confirmer la suppression",
      enterPasswords:
        "Entrez votre mot de passe deux fois pour supprimer le compte.",
      confirmPassword: "Confirmer le mot de passe",
      show: "Afficher",
      hide: "Masquer",
      deleting: "Suppression...",
      loadingTitle: "Chargement du profil",
      loadingSubtitle: "Nous récupérons vos informations et vos ruches.",
      modalDeleteHiveTitle: "Supprimer la ruche",
      modalDeleteHiveMessage:
        "Cette action est irréversible. Voulez-vous continuer ?",
      modalDuplicateTitle: "Dupliquer la ruche",
      modalDuplicateMessage: "Choisissez un nouveau nom pour la copie.",
      modalDuplicateInput: "Nom de la copie",
      modalDuplicateConfirm: "Créer la copie",
      modalCreateTitle: "Créer une nouvelle ruche",
      modalCreateMessage: "Choisissez un nom pour votre nouvelle ruche.",
      modalCreateInput: "Nom de la ruche",
      modalCreatePlaceholder:
        "Ex : Ruche projet Théâtre P2 école du renard 2024",
      missingPasswordFields:
        "Veuillez renseigner les deux champs de mot de passe.",
      passwordMismatch: "Les mots de passe ne correspondent pas.",
      duplicateNeedTitle: "Veuillez renseigner un titre pour la copie.",
      duplicateRenameRequired: "Renommez la copie avec un titre different.",
      copySuffix: "copie",
      emptyHive: "ruche vide",
      download: "Télécharger",
      downloading: "Téléchargement...",
      downloadFailed: "Erreur lors du téléchargement : {message}",
      searchLabel: "Rechercher une ruche",
      searchPlaceholder: "Nom de la ruche...",
      clearSearch: "Effacer la recherche",
      sortLabel: "Trier par",
      sortDateDesc: "Date (plus récentes)",
      sortDateAsc: "Date (plus anciennes)",
      sortNameAsc: "Nom (A-Z)",
      sortNameDesc: "Nom (Z-A)",
      noSearchResults: "Aucune ruche ne correspond à votre recherche.",
      modifyProfileTitle: "Modifier mon profil",
      modifyProfileDesc: "Mettez à jour votre rôle ou votre mot de passe.",
      changeRole: "Changer le rôle",
      changePassword: "Changer le mot de passe",
      updateRole: "Mettre à jour le rôle",
      updatingRole: "Mise à jour du rôle...",
      updatePassword: "Mettre à jour le mot de passe",
      updatingPassword: "Mise à jour du mot de passe...",
      currentPassword: "Mot de passe actuel",
      newPassword: "Nouveau mot de passe",
      newPasswordConfirm: "Confirmer le nouveau mot de passe",
      updateSuccess: "Profil mis à jour avec succès.",
      passwordUpdateSuccess: "Mot de passe mis à jour avec succès.",
      roleRequired: "Veuillez sélectionner un rôle.",
      roleOtherRequired: "Veuillez préciser votre rôle.",
      passwordUpdateRequiredFields:
        "Veuillez compléter les trois champs de mot de passe.",
      passwordTooShort:
        "Le nouveau mot de passe doit contenir au moins 8 caractères.",
    },
    inbox: {
      title: "Invitations",
      subtitle: "Acceptez ou refusez les demandes de collaboration.",
      loading: "Chargement des invitations...",
      empty: "Aucune invitation en attente.",
      invitedBy: "Invité par",
      role: "Rôle",
      sentAt: "Envoyé le",
      accept: "Accepter",
      accepting: "Acceptation...",
      decline: "Refuser",
      declining: "Refus...",
      unknownHive: "Ruche inconnue",
      loadError: "Impossible de charger les invitations.",
      actionError: "Action impossible pour cette invitation.",
    },
    admin: {
      title: "Administration",
      users: "Utilisateurs",
      hives: "Ruches",
      searchUsers: "Rechercher (nom, email, rôle)...",
      searchHives: "Rechercher (titre, propriétaire)...",
      user: "Utilisateur",
      role: "Rôle",
      hiveCount: "Ruches",
      collabs: "Collabs",
      comments: "Commentaires",
      createdAt: "Créé le",
      updatedAt: "Dernière édition",
      actions: "Actions",
      edit: "Modifier",
      cancelEdit: "Annuler",
      save: "Enregistrer",
      owner: "Propriétaire",
      titleLabel: "Titre",
      specify: "Précisez",
      deleteUser: "Supprimer l'utilisateur",
      deleteHive: "Supprimer la ruche",
      irreversible: "Cette action est irreversible. Voulez-vous continuer ?",
    },
    editor: {
      newHiveTitle: "Nouvelle Ruche",
      newDcoHiveTitle: "Nouvelle Ruche DCO",
      backToProfile: "Retour au profil",
      hiveTitleLabel: "Titre de la Ruche",
      saveHive: "Enregistrer la ruche",
      saving: "Enregistrement...",
      duplicateInfo:
        "Cette ruche est une copie. Renommez-la avant de l'enregistrer.",
      createdAt: "Créée le",
      updatedAt: "Dernière édition",
      updating: "Mise à jour en cours...",
      loadingTitle: "Chargement de la ruche",
      loadingSubtitle: "Les cartes et les commentaires arrivent.",
      commentsTitle: "Le buzz de la Ruche",
      noComments: "Aucun commentaire pour l'instant.",
      reply: "Répondre",
      edit: "Modifier",
      delete: "Supprimer",
      replyPlaceholder: "Écrire une réponse...",
      send: "Envoyer",
      addCommentPlaceholder: "Ajouter un commentaire...",
      unsavedTitle: "Modifications non enregistrées",
      unsavedMessage:
        "Votre ruche contient des modifications non enregistrées. Quitter sans sauvegarder ?",
      saveFirstTitle: "Enregistrez d'abord la ruche",
      saveFirstMessage:
        "Enregistrez votre ruche avant d'utiliser cette fonctionnalité.",
      stay: "Rester",
      saveAndLeave: "Enregistrer et quitter",
      leaveWithoutSaving: "Quitter sans enregistrer",
      editCommentTitle: "Modifier le commentaire",
      newMessage: "Nouveau message",
      deleteCommentTitle: "Supprimer le commentaire",
      saveTitleError: "Veuillez renseigner un titre avant d'enregistrer.",
      duplicateRenameError: "Renommez la copie avant de l'enregistrer.",
      renameOrDuplicateTitle: "Renommer ou créer une copie ?",
      renameOrDuplicateMessage:
        "Voulez-vous renommer la ruche existante '{oldTitle}' en '{newTitle}' ou créer une copie avec ce nouveau titre ?",
      renameOnly: "Renommer",
      createCopy: "Créer une copie",
      duplicateSuccess:
        "Copie créée avec succès ! La ruche '{newTitle}' a été créée et vous pouvez la retrouver dans votre profil.",
    },
    workspace: {
      cardNoteTitle: "Note de carte",
      showLibrary: "Afficher la bibliothèque",
      hideLibrary: "Masquer la bibliothèque",
      closeLibrary: "Fermer la bibliothèque",
      zoomOut: "-",
      zoomIn: "+",
      resetZoom: "100 %",
      fitContent: "Cadrer les cartes",
      fitBoard: "Vue d'ensemble",
      undo: "Annuler",
      redo: "Refaire",
      cardLabel: "Carte",
      createdBy: "Créé le {date} par {user}",
      updatedBy: "Dernière édition le {date} par {user}",
      noCardNote: "Aucune note pour cette carte.",
      addCardNotePlaceholder: "Ajouter une note à cette carte...",
      editCardNotePlaceholder: "Modifier la note de cette carte...",
      add: "Ajouter",
      continueDeleteCardNotes: "Continuer",
      deleteCardNotesTitle: "Supprimer les notes de carte",
      deleteSingleCardNoteMessage:
        "Cette carte contient une note. La remettre dans la bibliothèque supprimera cette note. Continuer ?",
      deleteMultipleCardNoteMessage:
        "Certaines cartes contiennent des notes. Les remettre dans la bibliothèque supprimera ces notes. Continuer ?",
      deleteCardNoteTitle: "Supprimer la note de carte",
      irreversible: "Cette action est irréversible. Voulez-vous continuer ?",
    },
    toolbar: {
      reset: "Réinitialiser",
      confirmResetTitle: "Réinitialiser la ruche",
      confirmResetMessage:
        "Voulez-vous vraiment réinitialiser la ruche ? Cette action supprimera toutes les cartes du plateau.",
      confirmReset: "Réinitialiser",
      screenshot: "Capture d'écran",
      collaborators: "Collaborateurs",
      comments: "Commentaires",
      manageCollaborators: "Gestion des collaborateurs",
      invite: "Inviter",
      inviting: "Invitation...",
      currentCollaborators: "Collaborateurs actuels",
      noCollaborators: "Aucun collaborateur pour le moment.",
      remove: "Retirer",
      leaveHive: "Quitter la ruche",
      leaving: "Sortie...",
      confirmLeaveTitle: "Quitter la ruche",
      confirmLeaveMessage: "Voulez-vous vraiment quitter cette ruche ?",
      confirmLeave: "Quitter",
      screenshotTitle: "Capture d'écran",
      roleAdmin: "Administrateur",
      roleEdit: "Collaborateur (peut éditer)",
      roleComment: "Commentaire uniquement",
      roleRead: "Lecture seule",
      inviteRequiredEmail:
        "Impossible d'envoyer l'invitation: l'email est obligatoire.",
      inviteInvalidEmail:
        "Impossible d'envoyer l'invitation: veuillez saisir un email valide.",
      inviteUnavailable: "Invitation indisponible pour le moment.",
      inviteNoUser:
        "Invitation impossible: aucun utilisateur n'existe avec cet email. Le collaborateur doit d'abord créer un compte.",
      inviteInvalid:
        "Invitation invalide: vérifiez l'email saisi puis réessayez.",
      inviteSent: "Invitation envoyée.",
      invitesLoadFailed: "Impossible de charger les invitations envoyées.",
      sentInvitations: "Invitations envoyées",
      noSentInvitations: "Aucune invitation envoyée pour le moment.",
      inviteStatusPending: "En attente",
      inviteStatusAccepted: "Acceptée",
      inviteStatusDeclined: "Refusée",
      inviteFailed: "Invitation impossible.",
      invalidRole: "Rôle invalide",
      removeFailed: "Impossible de retirer ce collaborateur",
      leaveFailed: "Impossible de quitter cette ruche",
      screenshotFailed: "Erreur lors de la capture : {message}",
      screenshotMergeError: "Impossible de générer l'image fusionnée.",
      frontBoardExportName: "plateau-recto",
      backBoardExportName: "plateau-verso",
      chatExportName: "chat-ruche",
      cardNotesExportName: "notes-cartes",
      cardNotesExportTitle: "Notes des cartes",
      noCardNotesExport: "Aucune carte du plateau ne contient de note.",
    },
    cardLibrary: {
      title: "Cartes disponibles",
      remaining: "restantes",
      freeCardTitle: "À vous de jouer !",
      maxFreeCardsReached:
        "Vous avez déjà atteint le maximum de 10 cartes libres !",
      searchLabel: "Rechercher une carte",
      searchPlaceholder: "Rechercher...",
      clearSearch: "Effacer la recherche",
      noResults: "Aucune carte ne correspond à votre recherche.",
    },
    addCardModal: {
      title: "À vous de jouer !",
      placeholder: "Entrez votre texte (max. 50 caractères)",
      emptyError: "Veuillez entrer un texte pour la carte.",
      validate: "Valider",
      close: "Fermer",
      customCards: "cartes personnalisées",
      colorLabel: "Couleur de la bordure :",
      colorCategories: {
        lime: "Carte libre",
        pink: "Domaines artistiques",
        purple: "Conditions & recommandations équipe",
        turquoise: "Visées & effets",
        orange: "Conditions & recommandations enseignant",
      },
    },
    passwordField: {
      showPassword: "Afficher le mot de passe",
    },
  },
  en: {
    common: {
      loading: "Loading...",
      close: "Close",
      cancel: "Cancel",
      save: "Save",
      edit: "Edit",
      delete: "Delete",
      confirm: "Confirm",
      page: "Page",
      previous: "Previous",
      next: "Next",
      unknownUser: "Unknown user",
      yes: "Yes",
      no: "No",
    },
    language: {
      label: "Language",
      fr: "Français",
      en: "English",
      nl: "Nederlands",
    },
    header: {
      profile: "Profile",
      inbox: "Inbox",
      admin: "Admin",
      logout: "Log out",
      login: "Log in",
      register: "Create account",
    },
    landing: {
      title: "Welcome to La Ruche",
      loading: "Loading your session...",
      connected: "Continue your work in just a few clicks.",
      guest: "Log in or create your account to get started.",
      goProfile: "Go to profile",
      createHive: "Create a Hive",
      learnMore: "Learn more",
      signIn: "Log in",
      createAccount: "Create account",
      tutorial: "Tutorial",
      tutorialPlaceholder: "Tutorial content coming soon...",
      gdpr: "GDPR / Privacy",
      gdprPlaceholder: "Privacy information coming soon...",
      wip: "Work in Progress",
      wipPlaceholder: "Next planned development steps coming soon...",
    },
    login: {
      title: "Log in",
      identifier: "Username or email",
      password: "Password",
      submit: "Log in",
      submitting: "Logging in...",
      forgot: "Forgot password?",
      noAccount: "No account yet?",
      register: "Sign up",
    },
    register: {
      title: "Create account",
      username: "Username (unique)",
      email: "Email",
      firstName: "First name",
      lastName: "Last name",
      role: "Role",
      roleOther: "Specify your role",
      password: "Password",
      passwordConfirm: "Confirm password",
      submit: "Create my account",
      submitting: "Creating...",
    },
    forgotPassword: {
      title: "Forgot password",
      email: "Email",
      submit: "Send link",
    },
    resetPassword: {
      invalidLink: "Invalid link",
      title: "New password",
      password: "Password",
      passwordConfirm: "Confirm password",
      submit: "Update",
    },
    protectedRoute: { loading: "Loading..." },
    profile: {
      title: "My profile",
      hivesTab: "My hives",
      settingsTab: "Edit profile",
      username: "Username",
      email: "Email",
      role: "Role",
      createNewHive: "Create a new Hive",
      modalselectHiveTypeTitle: "Hive type",
      selectHiveTypeMessage: "What type of hive do you want to create?",
      selectStandardHive: "Standard hive",
      selectDcoHive: "DCO hive",
      myHives: "My Hives",
      sharedHives: "Shared Hives",
      createdAt: "Created on",
      updatedAt: "Last edited",
      open: "Open",
      duplicate: "Duplicate",
      duplicating: "Duplicating...",
      deleteProfileTitle: "Delete my profile",
      deleteProfileDesc:
        "This action is irreversible and will delete your data.",
      confirmDeletion: "Confirm deletion",
      enterPasswords: "Enter your password twice to delete the account.",
      confirmPassword: "Confirm password",
      show: "Show",
      hide: "Hide",
      deleting: "Deleting...",
      loadingTitle: "Loading profile",
      loadingSubtitle: "We are retrieving your information and hives.",
      modalDeleteHiveTitle: "Delete hive",
      modalDeleteHiveMessage: "This action is irreversible. Continue?",
      modalDuplicateTitle: "Duplicate hive",
      modalDuplicateMessage: "Choose a new name for the copy.",
      modalDuplicateInput: "Copy name",
      modalDuplicateConfirm: "Create copy",
      modalCreateTitle: "Create a new hive",
      modalCreateMessage: "Choose a name for your new hive.",
      modalCreateInput: "Hive name",
      modalCreatePlaceholder:
        "Example: Theatre project hive P2 Fox School 2024",
      missingPasswordFields: "Please fill in both password fields.",
      passwordMismatch: "Passwords do not match.",
      duplicateNeedTitle: "Please provide a title for the copy.",
      duplicateRenameRequired: "Rename the copy with a different title.",
      copySuffix: "copy",
      emptyHive: "empty hive",
      download: "Download",
      downloading: "Downloading...",
      downloadFailed: "Download failed: {message}",
      searchLabel: "Search a hive",
      searchPlaceholder: "Hive name...",
      clearSearch: "Clear search",
      sortLabel: "Sort by",
      sortDateDesc: "Date (most recent)",
      sortDateAsc: "Date (oldest)",
      sortNameAsc: "Name (A-Z)",
      sortNameDesc: "Name (Z-A)",
      noSearchResults: "No hives match your search.",
      modifyProfileTitle: "Edit my profile",
      modifyProfileDesc: "Update your role or password.",
      changeRole: "Change role",
      changePassword: "Change password",
      updateRole: "Update role",
      updatingRole: "Updating role...",
      updatePassword: "Update password",
      updatingPassword: "Updating password...",
      currentPassword: "Current password",
      newPassword: "New password",
      newPasswordConfirm: "Confirm new password",
      updateSuccess: "Profile updated successfully.",
      passwordUpdateSuccess: "Password updated successfully.",
      roleRequired: "Please select a role.",
      roleOtherRequired: "Please specify your role.",
      passwordUpdateRequiredFields:
        "Please complete all three password fields.",
      passwordTooShort: "The new password must be at least 8 characters long.",
    },
    inbox: {
      title: "Invitations",
      subtitle: "Accept or decline collaboration requests.",
      loading: "Loading invitations...",
      empty: "No pending invitations.",
      invitedBy: "Invited by",
      role: "Role",
      sentAt: "Sent on",
      accept: "Accept",
      accepting: "Accepting...",
      decline: "Decline",
      declining: "Declining...",
      unknownHive: "Unknown hive",
      loadError: "Unable to load invitations.",
      actionError: "Unable to process this invitation.",
    },
    admin: {
      title: "Administration",
      users: "Users",
      hives: "Hives",
      searchUsers: "Search (name, email, role)...",
      searchHives: "Search (title, owner)...",
      user: "User",
      role: "Role",
      hiveCount: "Hives",
      collabs: "Collabs",
      comments: "Comments",
      createdAt: "Created on",
      updatedAt: "Last edited",
      actions: "Actions",
      edit: "Edit",
      cancelEdit: "Cancel",
      save: "Save",
      owner: "Owner",
      titleLabel: "Title",
      specify: "Specify",
      deleteUser: "Delete user",
      deleteHive: "Delete hive",
      irreversible: "This action is irreversible. Continue?",
    },
    editor: {
      newHiveTitle: "New Hive",
      newDcoHiveTitle: "New DCO Hive",
      backToProfile: "Back to profile",
      hiveTitleLabel: "Hive title",
      saveHive: "Save hive",
      saving: "Saving...",
      duplicateInfo: "This hive is a copy. Rename it before saving.",
      createdAt: "Created on",
      updatedAt: "Last edited",
      updating: "Updating...",
      loadingTitle: "Loading hive",
      loadingSubtitle: "Cards and comments are loading.",
      commentsTitle: "Hive chat",
      noComments: "No comments yet.",
      reply: "Reply",
      edit: "Edit",
      delete: "Delete",
      replyPlaceholder: "Write a reply...",
      send: "Send",
      addCommentPlaceholder: "Add a comment...",
      unsavedTitle: "Unsaved changes",
      unsavedMessage: "Your hive has unsaved changes. Leave without saving?",
      saveFirstTitle: "Save the hive first",
      saveFirstMessage: "Save your hive to access {feature}.",
      stay: "Stay",
      saveAndLeave: "Save and leave",
      leaveWithoutSaving: "Leave without saving",
      editCommentTitle: "Edit comment",
      newMessage: "New message",
      deleteCommentTitle: "Delete comment",
      saveTitleError: "Please provide a title before saving.",
      duplicateRenameError: "Rename the copy before saving.",
      renameOrDuplicateTitle: "Rename or create a copy?",
      renameOrDuplicateMessage:
        "Do you want to rename the existing hive '{oldTitle}' to '{newTitle}' or create a copy with this new title?",
      renameOnly: "Rename",
      createCopy: "Create a copy",
      duplicateSuccess:
        "Copy created successfully! The hive '{newTitle}' has been created and you can find it in your profile.",
    },
    workspace: {
      cardNoteTitle: "Card note",
      showLibrary: "Show library",
      hideLibrary: "Hide library",
      closeLibrary: "Close library",
      zoomOut: "-",
      zoomIn: "+",
      resetZoom: "100%",
      fitContent: "Fit cards",
      fitBoard: "Overview",
      undo: "Undo",
      redo: "Redo",
      cardLabel: "Card",
      createdBy: "Created on {date} by {user}",
      updatedBy: "Last edited on {date} by {user}",
      noCardNote: "No note for this card.",
      addCardNotePlaceholder: "Add a note to this card...",
      editCardNotePlaceholder: "Edit this card note...",
      add: "Add",
      continueDeleteCardNotes: "Continue",
      deleteCardNotesTitle: "Delete card notes",
      deleteSingleCardNoteMessage:
        "This card contains a note. Returning it to the library will delete that note. Continue?",
      deleteMultipleCardNoteMessage:
        "Some cards contain notes. Returning them to the library will delete those notes. Continue?",
      deleteCardNoteTitle: "Delete card note",
      irreversible: "This action is irreversible. Continue?",
    },
    toolbar: {
      reset: "Reset",
      confirmResetTitle: "Reset hive",
      confirmResetMessage:
        "Are you sure you want to reset the hive? This will remove all cards from the board.",
      confirmReset: "Reset",
      screenshot: "Screenshot",
      collaborators: "Collaborators",
      comments: "Comments",
      manageCollaborators: "Manage collaborators",
      invite: "Invite",
      inviting: "Inviting...",
      currentCollaborators: "Current collaborators",
      noCollaborators: "No collaborators yet.",
      remove: "Remove",
      leaveHive: "Leave hive",
      leaving: "Leaving...",
      confirmLeaveTitle: "Leave hive",
      confirmLeaveMessage: "Do you really want to leave this hive?",
      confirmLeave: "Leave",
      screenshotTitle: "Screenshot",
      roleAdmin: "Administrator",
      roleEdit: "Collaborator (can edit)",
      roleComment: "Comment only",
      roleRead: "Read only",
      inviteRequiredEmail: "Cannot send invitation: email is required.",
      inviteInvalidEmail: "Cannot send invitation: please enter a valid email.",
      inviteUnavailable: "Invitation is currently unavailable.",
      inviteNoUser:
        "Invitation failed: no user exists with this email. The collaborator must create an account first.",
      inviteInvalid: "Invalid invitation: check the email and try again.",
      inviteSent: "Invitation sent.",
      invitesLoadFailed: "Unable to load sent invitations.",
      sentInvitations: "Sent invitations",
      noSentInvitations: "No invitations sent yet.",
      inviteStatusPending: "Pending",
      inviteStatusAccepted: "Accepted",
      inviteStatusDeclined: "Declined",
      inviteFailed: "Invitation failed.",
      invalidRole: "Invalid role",
      removeFailed: "Cannot remove this collaborator",
      leaveFailed: "Cannot leave this hive",
      screenshotFailed: "Capture failed: {message}",
      screenshotMergeError: "Unable to create merged image.",
      frontBoardExportName: "front-board",
      backBoardExportName: "back-board",
      chatExportName: "hive-chat",
      cardNotesExportName: "card-notes",
      cardNotesExportTitle: "Card notes",
      noCardNotesExport: "No board card has a note.",
    },
    cardLibrary: {
      title: "Available cards",
      remaining: "remaining",
      freeCardTitle: "Your turn!",
      maxFreeCardsReached: "You already reached the maximum of 10 free cards!",
      searchLabel: "Search a card",
      searchPlaceholder: "Search...",
      clearSearch: "Clear search",
      noResults: "No cards match your search.",
    },
    addCardModal: {
      title: "Your turn!",
      placeholder: "Enter your text (max. 50 characters)",
      emptyError: "Please enter text for the card.",
      validate: "Validate",
      close: "Close",
      customCards: "custom cards",
      colorLabel: "Border color:",
      colorCategories: {
        lime: "Free card",
        pink: "Artistic domains",
        purple: "Team conditions & recommendations",
        turquoise: "Aims & impacts",
        orange: "Teacher conditions & recommendations",
      },
    },
    passwordField: { showPassword: "Show password" },
  },
  nl: {
    common: {
      loading: "Laden...",
      close: "Sluiten",
      cancel: "Annuleren",
      save: "Opslaan",
      edit: "Bewerken",
      delete: "Verwijderen",
      confirm: "Bevestigen",
      page: "Pagina",
      previous: "Vorige",
      next: "Volgende",
      unknownUser: "Onbekende gebruiker",
      yes: "Ja",
      no: "Nee",
    },
    language: {
      label: "Taal",
      fr: "Français",
      en: "English",
      nl: "Nederlands",
    },
    header: {
      profile: "Profiel",
      inbox: "Inbox",
      admin: "Admin",
      logout: "Afmelden",
      login: "Aanmelden",
      register: "Account aanmaken",
    },
    landing: {
      title: "Welkom bij La Ruche",
      loading: "Je sessie wordt geladen...",
      connected: "Ga verder met je werk in enkele klikken.",
      guest: "Meld je aan of maak een account om te starten.",
      goProfile: "Naar profiel",
      createHive: "Nieuwe Ruche maken",
      learnMore: "Meer informatie",
      signIn: "Aanmelden",
      createAccount: "Account aanmaken",
      tutorial: "Tutorial",
      tutorialPlaceholder: "Tutorial-inhoud komt binnenkort...",
      gdpr: "GDPR / Privacy",
      gdprPlaceholder: "Privacyinformatie komt binnenkort...",
      wip: "In Ontwikkeling",
      wipPlaceholder:
        "Volgende geplande ontwikkelingsstappen komen binnenkort...",
    },
    login: {
      title: "Aanmelden",
      identifier: "Gebruikersnaam of e-mail",
      password: "Wachtwoord",
      submit: "Aanmelden",
      submitting: "Bezig met aanmelden...",
      forgot: "Wachtwoord vergeten?",
      noAccount: "Nog geen account?",
      register: "Registreren",
    },
    register: {
      title: "Account aanmaken",
      username: "Gebruikersnaam (uniek)",
      email: "E-mail",
      firstName: "Voornaam",
      lastName: "Achternaam",
      role: "Rol",
      roleOther: "Specificeer je rol",
      password: "Wachtwoord",
      passwordConfirm: "Bevestig wachtwoord",
      submit: "Mijn account maken",
      submitting: "Bezig met aanmaken...",
    },
    forgotPassword: {
      title: "Wachtwoord vergeten",
      email: "E-mail",
      submit: "Link verzenden",
    },
    resetPassword: {
      invalidLink: "Ongeldige link",
      title: "Nieuw wachtwoord",
      password: "Wachtwoord",
      passwordConfirm: "Bevestig wachtwoord",
      submit: "Bijwerken",
    },
    protectedRoute: { loading: "Laden..." },
    profile: {
      title: "Mijn profiel",
      hivesTab: "Mijn bijenkorfen",
      settingsTab: "Profiel wijzigen",
      username: "Gebruikersnaam",
      email: "E-mail",
      role: "Rol",
      createNewHive: "Nieuwe Ruche maken",
      modalselectHiveTypeTitle: "Type bijenkorf",
      selectHiveTypeMessage: "Welk type bijenkorf wil je maken?",
      selectStandardHive: "Standaard bijenkorf",
      selectDcoHive: "DCO-bijenkorf",
      myHives: "Mijn Bijenkorfen",
      sharedHives: "Gedeelde Bijenkorfen",
      createdAt: "Gemaakt op",
      updatedAt: "Laatst bewerkt",
      open: "Openen",
      duplicate: "Dupliceren",
      duplicating: "Bezig met dupliceren...",
      deleteProfileTitle: "Mijn profiel verwijderen",
      deleteProfileDesc:
        "Deze actie is onomkeerbaar en verwijdert je gegevens.",
      confirmDeletion: "Verwijderen bevestigen",
      enterPasswords:
        "Voer je wachtwoord twee keer in om het account te verwijderen.",
      confirmPassword: "Wachtwoord bevestigen",
      show: "Tonen",
      hide: "Verbergen",
      deleting: "Bezig met verwijderen...",
      loadingTitle: "Profiel laden",
      loadingSubtitle: "We halen je gegevens en bijenkorfen op.",
      modalDeleteHiveTitle: "Bijenkorf verwijderen",
      modalDeleteHiveMessage: "Deze actie is onomkeerbaar. Wil je doorgaan?",
      modalDuplicateTitle: "Bijenkorf dupliceren",
      modalDuplicateMessage: "Kies een nieuwe naam voor de kopie.",
      modalDuplicateInput: "Naam van de kopie",
      modalDuplicateConfirm: "Kopie maken",
      modalCreateTitle: "Nieuwe bijenkorf maken",
      modalCreateMessage: "Kies een naam voor je nieuwe bijenkorf.",
      modalCreateInput: "Naam van de bijenkorf",
      modalCreatePlaceholder:
        "Bijv.: Bijenkorf theaterproject P2 Vossenschool 2024",
      missingPasswordFields: "Vul beide wachtwoordvelden in.",
      passwordMismatch: "Wachtwoorden komen niet overeen.",
      duplicateNeedTitle: "Geef een titel voor de kopie op.",
      duplicateRenameRequired: "Hernoem de kopie met een andere titel.",
      copySuffix: "kopie",
      emptyHive: "lege bijenkorf",
      download: "Downloaden",
      downloading: "Downloaden...",
      downloadFailed: "Download mislukt: {message}",
      searchLabel: "Zoek een bijenkorf",
      searchPlaceholder: "Naam van de bijenkorf...",
      clearSearch: "Zoekopdracht wissen",
      sortLabel: "Sorteren op",
      sortDateDesc: "Datum (meest recent)",
      sortDateAsc: "Datum (oudste)",
      sortNameAsc: "Naam (A-Z)",
      sortNameDesc: "Naam (Z-A)",
      noSearchResults: "Geen bijenkorven gevonden voor je zoekopdracht.",
      modifyProfileTitle: "Mijn profiel wijzigen",
      modifyProfileDesc: "Werk je rol of wachtwoord bij.",
      changeRole: "Rol wijzigen",
      changePassword: "Wachtwoord wijzigen",
      updateRole: "Rol bijwerken",
      updatingRole: "Rol wordt bijgewerkt...",
      updatePassword: "Wachtwoord bijwerken",
      updatingPassword: "Wachtwoord wordt bijgewerkt...",
      currentPassword: "Huidig wachtwoord",
      newPassword: "Nieuw wachtwoord",
      newPasswordConfirm: "Nieuw wachtwoord bevestigen",
      updateSuccess: "Profiel is succesvol bijgewerkt.",
      passwordUpdateSuccess: "Wachtwoord is succesvol bijgewerkt.",
      roleRequired: "Selecteer een rol.",
      roleOtherRequired: "Specificeer je rol.",
      passwordUpdateRequiredFields: "Vul alle drie de wachtwoordvelden in.",
      passwordTooShort:
        "Het nieuwe wachtwoord moet minstens 8 tekens bevatten.",
    },
    inbox: {
      title: "Uitnodigingen",
      subtitle: "Accepteer of weiger samenwerkingsverzoeken.",
      loading: "Uitnodigingen laden...",
      empty: "Geen openstaande uitnodigingen.",
      invitedBy: "Uitgenodigd door",
      role: "Rol",
      sentAt: "Verzonden op",
      accept: "Accepteren",
      accepting: "Bezig met accepteren...",
      decline: "Weigeren",
      declining: "Bezig met weigeren...",
      unknownHive: "Onbekende bijenkorf",
      loadError: "Uitnodigingen konden niet worden geladen.",
      actionError: "Deze uitnodiging kon niet worden verwerkt.",
    },
    admin: {
      title: "Beheer",
      users: "Gebruikers",
      hives: "Bijenkorfen",
      searchUsers: "Zoeken (naam, e-mail, rol)...",
      searchHives: "Zoeken (titel, eigenaar)...",
      user: "Gebruiker",
      role: "Rol",
      hiveCount: "Bijenkorfen",
      collabs: "Samenwerkingen",
      comments: "Reacties",
      createdAt: "Aangemaakt op",
      updatedAt: "Laatst bewerkt",
      actions: "Acties",
      edit: "Bewerken",
      cancelEdit: "Annuleren",
      save: "Opslaan",
      owner: "Eigenaar",
      titleLabel: "Titel",
      specify: "Specificeer",
      deleteUser: "Gebruiker verwijderen",
      deleteHive: "Bijenkorf verwijderen",
      irreversible: "Deze actie is onomkeerbaar. Wil je doorgaan?",
    },
    editor: {
      newHiveTitle: "Nieuwe Bijenkorf",
      newDcoHiveTitle: "Nieuwe DCO-bijenkorf",
      backToProfile: "Terug naar profiel",
      hiveTitleLabel: "Titel van de Bijenkorf",
      saveHive: "Bijenkorf opslaan",
      saving: "Opslaan...",
      duplicateInfo: "Deze bijenkorf is een kopie. Hernoem ze voor je opslaat.",
      createdAt: "Gemaakt op",
      updatedAt: "Laatst bewerkt",
      updating: "Bijwerken...",
      loadingTitle: "Bijenkorf laden",
      loadingSubtitle: "Kaarten en reacties worden geladen.",
      commentsTitle: "Bijenkorf-chat",
      noComments: "Nog geen reacties.",
      reply: "Antwoorden",
      edit: "Bewerken",
      delete: "Verwijderen",
      replyPlaceholder: "Schrijf een antwoord...",
      send: "Verzenden",
      addCommentPlaceholder: "Reactie toevoegen...",
      unsavedTitle: "Niet-opgeslagen wijzigingen",
      unsavedMessage:
        "Je bijenkorf bevat niet-opgeslagen wijzigingen. Verlaten zonder op te slaan?",
      saveFirstTitle: "Sla eerst de bijenkorf op",
      saveFirstMessage:
        "Sla je bijenkorf op om toegang te krijgen tot {feature}.",
      stay: "Blijven",
      saveAndLeave: "Opslaan en verlaten",
      leaveWithoutSaving: "Verlaten zonder opslaan",
      editCommentTitle: "Reactie bewerken",
      newMessage: "Nieuw bericht",
      deleteCommentTitle: "Reactie verwijderen",
      saveTitleError: "Vul een titel in voor je opslaat.",
      duplicateRenameError: "Hernoem de kopie voor je opslaat.",
      renameOrDuplicateTitle: "Hernoemen of kopie maken?",
      renameOrDuplicateMessage:
        "Wil je de bestaande bijenkorf '{oldTitle}' hernoemen naar '{newTitle}' of een kopie maken met deze nieuwe titel?",
      renameOnly: "Hernoemen",
      createCopy: "Kopie maken",
      duplicateSuccess:
        "Kopie met succes aangemaakt! De bijenkorf '{newTitle}' is aangemaakt en je kunt deze in je profiel vinden.",
    },
    workspace: {
      cardNoteTitle: "Kaartnotitie",
      showLibrary: "Bibliotheek tonen",
      hideLibrary: "Bibliotheek verbergen",
      closeLibrary: "Bibliotheek sluiten",
      zoomOut: "-",
      zoomIn: "+",
      resetZoom: "100%",
      fitContent: "Kaarten passend maken",
      fitBoard: "Overzicht",
      undo: "Ongedaan maken",
      redo: "Opnieuw",
      cardLabel: "Kaart",
      createdBy: "Aangemaakt op {date} door {user}",
      updatedBy: "Laatst bewerkt op {date} door {user}",
      noCardNote: "Geen notitie voor deze kaart.",
      addCardNotePlaceholder: "Voeg een notitie toe aan deze kaart...",
      editCardNotePlaceholder: "Bewerk de notitie van deze kaart...",
      add: "Toevoegen",
      continueDeleteCardNotes: "Doorgaan",
      deleteCardNotesTitle: "Kaartnotities verwijderen",
      deleteSingleCardNoteMessage:
        "Deze kaart bevat een notitie. Terugplaatsen in de bibliotheek verwijdert die notitie. Doorgaan?",
      deleteMultipleCardNoteMessage:
        "Sommige kaarten bevatten notities. Terugplaatsen in de bibliotheek verwijdert die notities. Doorgaan?",
      deleteCardNoteTitle: "Kaartnotitie verwijderen",
      irreversible: "Deze actie is onomkeerbaar. Wil je doorgaan?",
    },
    toolbar: {
      reset: "Resetten",
      confirmResetTitle: "Bijenkorf resetten",
      confirmResetMessage:
        "Weet je zeker dat je de bijenkorf wilt resetten? Dit verwijdert alle kaarten van het bord.",
      confirmReset: "Resetten",
      screenshot: "Schermafbeelding",
      collaborators: "Samenwerkers",
      comments: "Reacties",
      manageCollaborators: "Samenwerkers beheren",
      invite: "Uitnodigen",
      inviting: "Bezig met uitnodigen...",
      currentCollaborators: "Huidige samenwerkers",
      noCollaborators: "Nog geen samenwerkers.",
      remove: "Verwijderen",
      leaveHive: "Ruche verlaten",
      leaving: "Bezig met verlaten...",
      confirmLeaveTitle: "Ruche verlaten",
      confirmLeaveMessage: "Wil je deze ruche echt verlaten?",
      confirmLeave: "Verlaten",
      screenshotTitle: "Schermafbeelding",
      roleAdmin: "Beheerder",
      roleEdit: "Medewerker (kan bewerken)",
      roleComment: "Alleen reacties",
      roleRead: "Alleen lezen",
      inviteRequiredEmail:
        "Uitnodiging kan niet worden verzonden: e-mail is verplicht.",
      inviteInvalidEmail:
        "Uitnodiging kan niet worden verzonden: vul een geldig e-mailadres in.",
      inviteUnavailable: "Uitnodiging is momenteel niet beschikbaar.",
      inviteNoUser:
        "Uitnodiging mislukt: er bestaat geen gebruiker met dit e-mailadres. De samenwerker moet eerst een account aanmaken.",
      inviteInvalid:
        "Ongeldige uitnodiging: controleer het e-mailadres en probeer opnieuw.",
      inviteSent: "Uitnodiging verzonden.",
      invitesLoadFailed: "Verzonden uitnodigingen konden niet worden geladen.",
      sentInvitations: "Verzonden uitnodigingen",
      noSentInvitations: "Nog geen uitnodigingen verzonden.",
      inviteStatusPending: "In afwachting",
      inviteStatusAccepted: "Geaccepteerd",
      inviteStatusDeclined: "Geweigerd",
      inviteFailed: "Uitnodiging mislukt.",
      invalidRole: "Ongeldige rol",
      removeFailed: "Deze samenwerker kan niet worden verwijderd",
      leaveFailed: "Je kunt deze ruche niet verlaten",
      screenshotFailed: "Vastleggen mislukt: {message}",
      screenshotMergeError: "Samengevoegde afbeelding kon niet worden gemaakt.",
      frontBoardExportName: "bord-voorzijde",
      backBoardExportName: "bord-achterzijde",
      chatExportName: "bijenkorf-chat",
      cardNotesExportName: "kaartnotities",
      cardNotesExportTitle: "Kaartnotities",
      noCardNotesExport: "Geen enkele kaart op het bord heeft een notitie.",
    },
    cardLibrary: {
      title: "Beschikbare kaarten",
      remaining: "over",
      freeCardTitle: "Jij bent aan zet!",
      maxFreeCardsReached:
        "Je hebt al het maximum van 10 vrije kaarten bereikt!",
      searchLabel: "Een kaart zoeken",
      searchPlaceholder: "Zoeken...",
      clearSearch: "Zoekopdracht wissen",
      noResults: "Geen kaarten komen overeen met uw zoekopdracht.",
    },
    addCardModal: {
      title: "Jij bent aan zet!",
      placeholder: "Vul je tekst in (max. 50 tekens)",
      emptyError: "Vul tekst in voor de kaart.",
      validate: "Bevestigen",
      close: "Sluiten",
      customCards: "aangepaste kaarten",
      colorLabel: "Randkleur:",
      colorCategories: {
        lime: "Vrije kaart",
        pink: "Artistieke domeinen",
        purple: "Voorwaarden & aanbevelingen team",
        turquoise: "Doelen & effecten",
        orange: "Voorwaarden & aanbevelingen leerkracht",
      },
    },
    passwordField: { showPassword: "Wachtwoord tonen" },
  },
};

function normalizeText(value) {
  return String(value || "")
    .trim()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase();
}

const roleLookupByNormalized = new Map(
  USER_ROLES.map((role) => [normalizeText(role), role]),
);

function resolveCanonicalRole(value) {
  if (!value) return "";
  return roleLookupByNormalized.get(normalizeText(value)) || String(value);
}

function getMessageByPath(obj, path) {
  return path.split(".").reduce((acc, key) => {
    if (!acc || typeof acc !== "object") return undefined;
    return acc[key];
  }, obj);
}

function interpolate(template, params) {
  if (!params) return template;
  return Object.entries(params).reduce(
    (result, [key, value]) =>
      result.replace(new RegExp(`\\{${key}\\}`, "g"), String(value)),
    template,
  );
}

function getInitialLanguage() {
  const stored = window.localStorage.getItem(STORAGE_KEY);
  if (SUPPORTED_LANGUAGES.includes(stored)) return stored;

  const browserLang = (navigator.language || "").slice(0, 2).toLowerCase();
  return SUPPORTED_LANGUAGES.includes(browserLang)
    ? browserLang
    : DEFAULT_LANGUAGE;
}

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => {
    const t = (path, params) => {
      const current = getMessageByPath(messages[language], path);
      const fallback = getMessageByPath(messages[DEFAULT_LANGUAGE], path);
      const resolved = current ?? fallback;

      if (typeof resolved !== "string") {
        return path;
      }

      return interpolate(resolved, params);
    };

    const translateRole = (roleLabel) => {
      const canonical = resolveCanonicalRole(roleLabel);
      return ROLE_LABELS[language][canonical] || canonical;
    };

    return {
      language,
      setLanguage,
      supportedLanguages: SUPPORTED_LANGUAGES,
      t,
      dateLocale: DATE_LOCALES[language],
      roleOptions: USER_ROLES.map((value) => ({
        value,
        label: ROLE_LABELS[language][value] || value,
      })),
      translateRole,
      cardCategories: CARD_CATEGORIES[language],
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
