export const STORAGE_KEY = "ruche-language";
export const SUPPORTED_LANGUAGES = ["fr", "en", "nl"];
export const DEFAULT_LANGUAGE = "fr";

export const DATE_LOCALES = {
  fr: "fr-BE",
  en: "en-GB",
  nl: "nl-BE",
};

export const USER_ROLES = [
  "Délégué PECA",
  "Délégué au Contrat d'Objectifs",
  "Direction",
  "Enseignant",
  "Éducateur",
  "Membre d'un CPMS",
  "Futur enseignant",
  "Intervenant culturel",
  "Étudiant en École Supérieure des Arts",
  "Référent culturel",
  "Référent scolaire",
  "Autre",
];

export const ROLE_LABELS = {
  fr: {
    "Délégué PECA": "Délégué PECA",
    "Délégué au Contrat d'Objectifs": "Délégué au Contrat d'Objectifs",
    Direction: "Direction",
    Enseignant: "Enseignant",
    Éducateur: "Éducateur",
    "Membre d'un CPMS": "Membre d'un CPMS",
    "Futur enseignant": "Futur enseignant",
    "Intervenant culturel": "Intervenant culturel",
    "Étudiant en École Supérieure des Arts":
      "Étudiant en École Supérieure des Arts",
    "Référent culturel": "Référent culturel",
    "Référent scolaire": "Référent scolaire",
    Autre: "Autre",
  },
  en: {
    "Délégué PECA": "PECA representative",
    "Délégué au Contrat d'Objectifs": "Objectives Contract delegate",
    Direction: "School leadership",
    Enseignant: "Teacher",
    Éducateur: "Educator",
    "Membre d'un CPMS": "CPMS member",
    "Futur enseignant": "Future teacher",
    "Intervenant culturel": "Cultural practitioner",
    "Étudiant en École Supérieure des Arts": "Arts college student",
    "Référent culturel": "Cultural coordinator",
    "Référent scolaire": "School coordinator",
    Autre: "Other",
  },
  nl: {
    "Délégué PECA": "PECA-afgevaardigde",
    "Délégué au Contrat d'Objectifs":
      "Afgevaardigde van het doelstellingencontract",
    Direction: "Directie",
    Enseignant: "Leerkracht",
    Éducateur: "Opvoeder",
    "Membre d'un CPMS": "Lid van een CLB",
    "Futur enseignant": "Toekomstige leerkracht",
    "Intervenant culturel": "Cultureel begeleider",
    "Étudiant en École Supérieure des Arts": "Student aan een kunsthogeschool",
    "Référent culturel": "Cultureel referentiepersoon",
    "Référent scolaire": "Schoolreferentiepersoon",
    Autre: "Andere",
  },
};

export const CARD_CATEGORIES = {
  fr: [
    { key: "domaine", label: "Domaines d'expression culturelle et artistique" },
    {
      key: "conditions-enseignant",
      label: "Conditions pour l'enseignant/intervenant",
    },
    {
      key: "recommandations-enseignant",
      label: "Recommandations pour l'enseignant/intervenant",
    },
    { key: "visees", label: "Visées & effets pour les élèves" },
    { key: "conditions-equipe", label: "Conditions pour l'équipe éducative" },
    {
      key: "recommandations-equipe",
      label: "Recommandations pour l'équipe éducative",
    },
    { key: "free", label: "À vous de jouer !" },
  ],
  en: [
    { key: "domaine", label: "Cultural and artistic expression domains" },
    {
      key: "conditions-enseignant",
      label: "Conditions for teachers/practitioners",
    },
    {
      key: "recommandations-enseignant",
      label: "Recommendations for teachers/practitioners",
    },
    { key: "visees", label: "Aims & impacts for students" },
    { key: "conditions-equipe", label: "Conditions for the educational team" },
    {
      key: "recommandations-equipe",
      label: "Recommendations for the educational team",
    },
    { key: "free", label: "Your turn!" },
  ],
  nl: [
    { key: "domaine", label: "Domeinen van culturele en artistieke expressie" },
    {
      key: "conditions-enseignant",
      label: "Voorwaarden voor leerkrachten/begeleiders",
    },
    {
      key: "recommandations-enseignant",
      label: "Aanbevelingen voor leerkrachten/begeleiders",
    },
    { key: "visees", label: "Doelen & effecten voor leerlingen" },
    { key: "conditions-equipe", label: "Voorwaarden voor het schoolteam" },
    {
      key: "recommandations-equipe",
      label: "Aanbevelingen voor het schoolteam",
    },
    { key: "free", label: "Jij bent aan zet!" },
  ],
};

export const messages = {
  fr: {
    common: {
      loading: "Chargement...",
      close: "Fermer",
      cancel: "Annuler",
      save: "Enregistrer",
      edit: "Modifier",
      delete: "Supprimer",
      confirm: "Confirmer",
      page: "Page",
      previous: "Précédent",
      next: "Suivant",
      charactersLeft: "{count} caractères restants",
      unknownUser: "Utilisateur inconnu",
      yes: "Oui",
      no: "Non",
      unexpectedError: "Une erreur inattendue est survenue.",
    },
    apiErrors: {
      AUTH_REQUIRED: "Authentification requise.",
      AUTH_INVALID_USER: "Utilisateur invalide.",
      AUTH_SESSION_INVALID: "Session invalide ou expirée.",
      AUTH_ADMIN_REQUIRED: "Accès administrateur requis.",
      AUTH_INVALID_CREDENTIALS: "Identifiants invalides.",
      AUTH_USERNAME_TAKEN: "Nom d'utilisateur déjà utilisé.",
      AUTH_EMAIL_TAKEN: "Email déjà utilisé.",
      AUTH_INVALID_EMAIL: "Email invalide.",
      AUTH_RESET_LINK_INVALID: "Lien invalide ou expiré.",
      VALIDATION_INVALID_DATA: "Données invalides.",
      VALIDATION_INVALID_ROLE: "Rôle invalide.",
      VALIDATION_ROLE_REQUIRED: "Veuillez préciser votre rôle.",
      PASSWORDS_DO_NOT_MATCH: "Les mots de passe ne correspondent pas.",
      PROFILE_USER_NOT_FOUND: "Utilisateur introuvable.",
      PROFILE_PASSWORD_CURRENT_INCORRECT: "Mot de passe actuel incorrect.",
      PROFILE_CONFIRMATION_INVALID: "Confirmation invalide.",
      PROFILE_CONFIRM_DELETE_REQUIRED: "Veuillez confirmer avec DELETE.",
      PROFILE_PASSWORD_INCORRECT: "Mot de passe incorrect.",
      PROFILE_PASSWORD_CHANGE_FIELDS_REQUIRED:
        "Veuillez renseigner le mot de passe actuel et confirmer le nouveau mot de passe.",
      HIVE_NOT_FOUND: "Ruche introuvable.",
      HIVE_ACCESS_DENIED: "Accès refusé.",
      HIVE_INVALID_DATA: "Données de ruche invalides.",
      HIVE_TITLE_TOO_LONG:
        "Le titre de la ruche doit contenir au maximum 100 caracteres.",
      HIVE_EDIT_FORBIDDEN:
        "Vous n'avez pas l'autorisation de modifier cette ruche.",
      HIVE_RENAME_FORBIDDEN:
        "Vous n'avez pas l'autorisation de renommer cette ruche.",
      HIVE_VERSION_INVALID: "Version de ruche invalide.",
      HIVE_VERSION_REQUIRED:
        "Version de ruche manquante. Rechargez la ruche avant d'enregistrer.",
      HIVE_VERSION_CONFLICT:
        "Cette ruche a été modifiée par un autre collaborateur. Rechargez-la avant d'enregistrer.",
      HIVE_CARD_NOTE_INVALID: "Note de carte invalide.",
      HIVE_CARD_NOTE_FORBIDDEN:
        "Vous n'avez pas l'autorisation d'ajouter des notes sur cette ruche.",
      HIVE_CARD_NOTE_CARD_NOT_FOUND:
        "Cette carte est introuvable dans la ruche.",
      HIVE_COMMENT_INVALID: "Commentaire invalide.",
      HIVE_COMMENT_FORBIDDEN:
        "Vous n'avez pas l'autorisation de commenter cette ruche.",
      HIVE_COMMENT_PARENT_NOT_FOUND: "Commentaire parent introuvable.",
      HIVE_COMMENT_NOT_FOUND: "Commentaire introuvable.",
      HIVE_COMMENT_LIMIT_REACHED:
        "Le nombre maximum de commentaires a été atteint pour cette ruche.",
      HIVE_COMMENT_RATE_LIMIT:
        "Vous commentez trop vite. Veuillez réessayer dans un instant.",
      HIVE_COMMENT_EDIT_OWN_ONLY:
        "Vous ne pouvez modifier que vos propres commentaires.",
      HIVE_COMMENT_DELETE_OWN_ONLY:
        "Vous ne pouvez supprimer que vos propres commentaires.",
    },
    apiMessages: {
      MSG_PASSWORD_RESET_EMAIL_SENT:
        "Si le compte existe, un email a été envoyé.",
      MSG_PASSWORD_UPDATED: "Mot de passe mis à jour.",
      MSG_PROFILE_UPDATED: "Profil mis à jour.",
      MSG_PROFILE_DELETED: "Profil supprimé.",
    },
    language: {
      label: "Langue",
      fr: "Français",
      en: "English",
      nl: "Nederlands",
    },
    header: {
      profile: "Profil",
      inbox: "Boîte de réception",
      admin: "Admin",
      logout: "Déconnexion",
      login: "Connexion",
      register: "Créer un compte",
      hiveMenu: "Menu ruche",
      accountMenu: "Mon compte",
    },
    landing: {
      title: "Bienvenue dans La Ruche",
      loading: "Chargement de votre session...",
      connected: "Continuez votre activité en quelques clics.",
      guest: "Connectez-vous ou créez votre compte pour commencer.",
      goProfile: "Accéder au profil",
      createHive: "Créer une Ruche",
      learnMore: "En savoir plus",
      signIn: "Se connecter",
      createAccount: "Créer un compte",
      tutorial: "Tutoriel",
      tutorialPlaceholder: "Guide complet et vidéo d'explication",
      gdpr: "RGPD / Confidentialité",
      gdprPlaceholder: "Données, cookies, droits RGPD — lisez notre politique.",
      reportBug: "Signaler un bug",
      wip: "En cours de développement",
      wipPlaceholder:
        "V1, V2, fonctionnalités à venir — découvrez la feuille de route.",
      contact: "Contact",
    },
    login: {
      title: "Connexion",
      identifier: "Nom d'utilisateur ou email",
      password: "Mot de passe",
      submit: "Se connecter",
      submitting: "Connexion...",
      forgot: "Mot de passe oublié ?",
      noAccount: "Pas encore de compte ?",
      register: "Inscription",
    },
    register: {
      charactersLeft: "{count} caractères restants",
      title: "Créer un compte",
      requiredNotice: "Tous les champs sont obligatoires.",
      username: "Nom d'utilisateur (unique)",
      email: "Email",
      firstName: "Prénom",
      lastName: "Nom",
      role: "Rôle",
      roleOther: "Précisez votre rôle",
      password: "Mot de passe",
      passwordConfirm: "Confirmation du mot de passe",
      submit: "Créer mon compte",
      submitting: "Création...",
    },
    forgotPassword: {
      title: "Mot de passe oublié",
      email: "Email",
      submit: "Envoyer le lien",
      submitting: "Envoi en cours...",
    },
    resetPassword: {
      invalidLink: "Lien invalide",
      title: "Nouveau mot de passe",
      password: "Mot de passe",
      passwordConfirm: "Confirmer le mot de passe",
      submit: "Mettre à jour",
      submitting: "Mise à jour en cours...",
    },
    protectedRoute: {
      loading: "Chargement...",
    },
    profile: {
      title: "Mon profil",
      hivesTab: "Mes ruches",
      settingsTab: "Modifier mon profil",
      username: "Nom d'utilisateur",
      email: "Email",
      firstname: "Prénom",
      lastname: "Nom",
      role: "Rôle",
      createNewHive: "Créer une nouvelle Ruche",
      modalselectHiveTypeTitle: "Type de ruche",
      selectHiveTypeMessage: "Quel type de ruche voulez-vous créer ?",
      selectStandardHive: "Ruche standard",
      selectDcoHive: "Ruche DCO",
      myHives: "Mes Ruches",
      sharedHives: "Ruches partagées",
      createdAt: "Créée le",
      updatedAt: "Dernière édition",
      open: "Ouvrir",
      renameHive: "Renommer la ruche",
      duplicate: "Dupliquer",
      duplicating: "La ruche est dupliquée...",
      renaming: "La ruche est renommée...",
      deleteProfileTitle: "Supprimer mon profil",
      deleteProfileDesc:
        "Cette action est irréversible et supprimera vos données.",
      confirmDeletion: "Confirmer la suppression",
      enterPasswords:
        "Entrez votre mot de passe deux fois pour supprimer le compte.",
      confirmPassword: "Confirmer le mot de passe",
      show: "Afficher",
      hide: "Masquer",
      deleting: "Suppression...",
      loadingTitle: "Chargement du profil",
      loadingSubtitle: "Nous récupérons vos informations et vos ruches.",
      modalDeleteHiveTitle: "Supprimer la ruche",
      modalDeleteHiveMessage:
        "Cette action est irréversible. Voulez-vous continuer ?",
      modalDuplicateTitle: "Dupliquer la ruche",
      modalDuplicateMessage: "Choisissez un nouveau nom pour la copie.",
      modalDuplicateInput: "Nom de la copie",
      modalDuplicateConfirm: "Créer la copie",
      modalCreateTitle: "Créer une nouvelle ruche",
      modalCreateMessage: "Choisissez un nom pour votre nouvelle ruche.",
      modalCreateInput: "Nom de la ruche",
      modalCreatePlaceholder:
        "Ex : Ruche projet Théâtre P2 école du renard 2024",
      missingPasswordFields:
        "Veuillez renseigner les deux champs de mot de passe.",
      passwordMismatch: "Les mots de passe ne correspondent pas.",
      duplicateNeedTitle: "Veuillez renseigner un titre pour la copie.",
      duplicateRenameRequired: "Renommez la copie avec un titre différent.",
      copySuffix: "copie",
      emptyHive: "ruche vide",
      download: "Télécharger",
      downloading: "Téléchargement...",
      downloadFailed: "Erreur lors du téléchargement : {message}",
      searchLabel: "Rechercher une ruche",
      searchPlaceholder: "Nom de la ruche...",
      clearSearch: "Effacer la recherche",
      sortLabel: "Trier par",
      filterLabel: "Filtrer",
      filterAll: "Toutes les ruches",
      sortDateDesc: "Date (plus récentes)",
      sortDateAsc: "Date (plus anciennes)",
      sortNameAsc: "Nom (A-Z)",
      sortNameDesc: "Nom (Z-A)",
      noSearchResults: "Aucune ruche ne correspond à votre recherche.",
      modifyProfileTitle: "Modifier mon profil",
      modifyProfileDesc: "Mettez à jour votre rôle ou votre mot de passe.",
      changeRole: "Changer le rôle",
      changePassword: "Changer le mot de passe",
      updateRole: "Mettre à jour le rôle",
      updatingRole: "Mise à jour du rôle...",
      updatePassword: "Mettre à jour le mot de passe",
      updatingPassword: "Mise à jour du mot de passe...",
      currentPassword: "Mot de passe actuel",
      newPassword: "Nouveau mot de passe",
      newPasswordConfirm: "Confirmer le nouveau mot de passe",
      updateSuccess: "Profil mis à jour avec succès.",
      passwordUpdateSuccess: "Mot de passe mis à jour avec succès.",
      roleRequired: "Veuillez sélectionner un rôle.",
      roleOtherRequired: "Veuillez préciser votre rôle.",
      passwordUpdateRequiredFields:
        "Veuillez compléter les trois champs de mot de passe.",
      passwordTooShort:
        "Le nouveau mot de passe doit contenir au moins 8 caractères.",
    },
    inbox: {
      title: "Invitations",
      subtitle: "Acceptez ou refusez les demandes de collaboration.",
      loading: "Chargement des invitations...",
      empty: "Aucune invitation en attente.",
      invitedBy: "Invité par",
      role: "Rôle",
      sentAt: "Envoyé le",
      accept: "Accepter",
      accepting: "Acceptation...",
      decline: "Refuser",
      declining: "Refus...",
      unknownHive: "Ruche inconnue",
      loadError: "Impossible de charger les invitations.",
      actionError: "Action impossible pour cette invitation.",
    },
    admin: {
      title: "Administration",
      users: "Utilisateurs",
      hives: "Ruches",
      searchUsers: "Rechercher (nom, email, rôle)...",
      searchHives: "Rechercher (titre, propriétaire)...",
      user: "Utilisateur",
      role: "Rôle",
      hiveCount: "Ruches",
      collabs: "Collabs",
      comments: "Commentaires",
      charactersLeft: "{count} caractères restants",
      createdAt: "Créé le",
      updatedAt: "Dernière édition",
      lastActivityAt: "Dernière activité",
      actions: "Actions",
      edit: "Modifier",
      cancelEdit: "Annuler",
      save: "Enregistrer",
      owner: "Propriétaire",
      titleLabel: "Titre",
      specify: "Précisez",
      deleteUser: "Supprimer l'utilisateur",
      deleteHive: "Supprimer la ruche",
      irreversible: "Cette action est irréversible. Voulez-vous continuer ?",
      confirmDeleteFinal: "Confirmation finale",
      doubleConfirmMessage:
        "Êtes-vous vraiment sûr(e) de vouloir supprimer cet élément ?",
      viewHive: "Voir",
      hiveDetails: "Détails de la ruche",
      hiveCollaborators: "Collaborateurs",
      hiveComments: "Commentaires",
      noCollaborators: "Aucun collaborateur.",
      noComments: "Aucun commentaire.",
      removeCollaborator: "Retirer",
      confirmRemoveCollaborator: "Retirer ce collaborateur ?",
      confirmRemoveMessage:
        "Voulez-vous retirer ce collaborateur de la ruche ?",
      confirmDeleteComment: "Supprimer ce commentaire ?",
      deleting: "Suppression...",
      removingCollaborator: "Retrait...",
      deletingComment: "Suppression du commentaire...",
    },
    editor: {
      newHiveTitle: "Nouvelle Ruche",
      newDcoHiveTitle: "Nouvelle Ruche DCO",
      backToProfile: "Mes ruches",
      hiveTitleLabel: "Titre de la Ruche",
      saveHive: "Enregistrer la ruche",
      saving: "Enregistrement...",
      duplicateInfo:
        "Cette ruche est une copie. Renommez-la avant de l'enregistrer.",
      createdAt: "Créée le",
      updatedAt: "Dernière édition",
      updating: "Mise à jour en cours...",
      loadingTitle: "Chargement de la ruche",
      loadingSubtitle: "Les cartes et les commentaires arrivent.",
      commentsTitle: "Le buzz de la Ruche",
      noComments: "Aucun commentaire pour l'instant.",
      reply: "Répondre",
      edit: "Modifier",
      delete: "Supprimer",
      replyPlaceholder: "Écrire une réponse...",
      send: "Envoyer",
      sending: "Envoi en cours...",
      addCommentPlaceholder: "Ajouter un commentaire...",
      loadOlderComments: "Charger les commentaires plus anciens",
      loadingOlderComments: "Chargement des anciens commentaires...",
      commentsMaxReached:
        "Nombre maximum de commentaires atteint pour cette ruche.",
      unsavedTitle: "Modifications non enregistrées",
      unsavedMessage:
        "Votre ruche contient des modifications non enregistrées. Quitter sans sauvegarder ?",
      saveFirstTitle: "Enregistrez d'abord la ruche",
      saveFirstMessage:
        "Enregistrez votre ruche avant d'utiliser cette fonctionnalité.",
      stay: "Rester",
      saveAndLeave: "Enregistrer et quitter",
      leaveWithoutSaving: "Quitter sans enregistrer",
      editCommentTitle: "Modifier le commentaire",
      newMessage: "Nouveau message",
      deleteCommentTitle: "Supprimer le commentaire",
      updatingComment: "Mise à jour du commentaire...",
      deletingComment: "Suppression du commentaire...",
      saveTitleError: "Veuillez renseigner un titre avant d'enregistrer.",
      duplicateRenameError: "Renommez la copie avant de l'enregistrer.",
      saveStatusSaving: "Enregistrement en cours...",
      saveStatusSaved: "Ruche enregistrée.",
      saveStatusError: "Échec de l'enregistrement.",
      renameOrDuplicateTitle: "Renommer ou créer une copie ?",
      renameOrDuplicateMessage:
        "Voulez-vous renommer la ruche existante '{oldTitle}' en '{newTitle}' ou créer une copie avec ce nouveau titre ?",
      renameOnly: "Renommer",
      createCopy: "Créer une copie",
      duplicateSuccess:
        "Copie créée avec succès ! La ruche '{newTitle}' a été créée et vous pouvez la retrouver dans votre profil.",
      conflictTitle: "Mise à jour concurrente détectée",
      conflictMessage:
        "Un autre collaborateur a enregistré cette ruche avant vous. Rechargez la dernière version ou créez une copie pour conserver votre travail.",
      conflictReload: "Recharger la dernière version",
      activeEditorsOthers: "Collaborateurs en cours d'édition : {names}",
      activeEditorsOnlyYou: "Vous éditez actuellement cette ruche.",
    },
    workspace: {
      cardNoteTitle: "Note de carte",
      editNotAllowed: "Vous ne pouvez pas modifier cette ruche.",
      showLibrary: "Afficher la bibliothèque",
      hideLibrary: "Masquer la bibliothèque",
      closeLibrary: "Fermer la bibliothèque",
      enableMultiSelect: "Sélection multiple",
      disableMultiSelect: "Fin de la sélection multiple",
      returnSelectedToLibrary: "Renvoyer à la bibliothèque ({count})",
      returnSingleSelectedToLibrary: "Renvoyer la carte",
      selectAll: "Tout sélectionner",
      tabletSelectHint: "Toucher une carte pour la sélectionner",
      zoomOut: "-",
      zoomIn: "+",
      resetZoom: "100 %",
      fitContent: "Cadrer les cartes",
      fitBoard: "Vue d'ensemble",
      undo: "Annuler",
      redo: "Refaire",
      cardLabel: "Carte",
      createdBy: "Créé le {date} par {user}",
      updatedBy: "Dernière édition le {date} par {user}",
      noCardNote: "Aucune note pour cette carte.",
      cardNoteReadOnlyHint:
        "Vous pouvez consulter cette note, mais pas la modifier.",
      cardNoteSaveFirst:
        "Sauvegardez votre ruche pour accéder aux notes de carte.",
      addCardNotePlaceholder: "Ajouter une note à cette carte...",
      editCardNotePlaceholder: "Modifier la note de cette carte...",
      add: "Ajouter",
      continueDeleteCardNotes: "Continuer",
      deleteCardNotesTitle: "Supprimer les notes de carte",
      deleteSingleCardNoteMessage:
        "Cette carte contient une note. La remettre dans la bibliothèque supprimera cette note. Continuer ?",
      deleteMultipleCardNoteMessage:
        "Certaines cartes contiennent des notes. Les remettre dans la bibliothèque supprimera ces notes. Continuer ?",
      deleteCardNoteTitle: "Supprimer la note de carte",
      deletingCardNote: "Suppression de la note...",
      irreversible: "Cette action est irréversible. Voulez-vous continuer ?",
      historyLimitReached:
        "Historique limite atteint ({count} actions). Les actions les plus anciennes sont oubliées.",
      tabletOnlyMessage:
        "L'éditeur est optimisé pour ordinateur et tablette en mode paysage. Passez en paysage sur tablette pour continuer.",
    },
    toolbar: {
      reset: "Réinitialiser",
      confirmResetTitle: "Réinitialiser la ruche",
      confirmResetMessage:
        "Voulez-vous vraiment réinitialiser la ruche ? Cette action supprimera toutes les cartes du plateau.",
      confirmReset: "Réinitialiser",
      export: "Exporter",
      exporting: "Export en cours...",
      collaborators: "Collaborateurs",
      comments: "Commentaires",
      manageCollaborators: "Gestion des collaborateurs",
      invite: "Inviter",
      inviting: "Invitation...",
      currentCollaborators: "Collaborateurs actuels",
      noCollaborators: "Aucun collaborateur pour le moment.",
      remove: "Retirer",
      leaveHive: "Quitter la ruche",
      leaving: "Sortie...",
      confirmLeaveTitle: "Quitter la ruche",
      confirmLeaveMessage: "Voulez-vous vraiment quitter cette ruche ?",
      confirmLeave: "Quitter",
      exportTitle: "Export de la ruche",
      roleAdmin: "Administrateur",
      roleEdit: "Collaborateur (peut éditer)",
      roleComment: "Commentaire uniquement",
      roleRead: "Lecture seule",
      inviteRequiredEmail:
        "Impossible d'envoyer l'invitation: l'email est obligatoire.",
      inviteInvalidEmail:
        "Impossible d'envoyer l'invitation: veuillez saisir un email valide.",
      inviteUnavailable: "Invitation indisponible pour le moment.",
      inviteNoUser:
        "Invitation impossible: aucun utilisateur n'existe avec cet email. Le collaborateur doit d'abord créer un compte.",
      inviteInvalid:
        "Invitation invalide: vérifiez l'email saisi puis réessayez.",
      inviteSent: "Invitation envoyée.",
      invitesLoadFailed: "Impossible de charger les invitations envoyées.",
      sentInvitations: "Invitations envoyées",
      noSentInvitations: "Aucune invitation envoyée pour le moment.",
      inviteStatusPending: "En attente",
      inviteStatusAccepted: "Acceptée",
      inviteStatusDeclined: "Refusée",
      inviteFailed: "Invitation impossible.",
      invalidRole: "Rôle invalide",
      removeFailed: "Impossible de retirer ce collaborateur",
      leaveFailed: "Impossible de quitter cette ruche",
      exportFailed: "Erreur lors de l'export : {message}",
      exportMergeError: "Impossible de générer l'export fusionne.",
      frontBoardExportName: "plateau-recto",
      backBoardExportName: "plateau-verso",
      chatExportName: "chat-ruche",
      cardNotesExportName: "notes-cartes",
      cardNotesExportTitle: "Notes des cartes",
      noCardNotesExport: "Aucune carte du plateau ne contient de note.",
    },
    cardLibrary: {
      title: "Cartes disponibles",
      remaining: "restantes",
      freeCardTitle: "À vous de jouer !",
      editNotAllowed: "Vous ne pouvez pas modifier cette ruche.",
      maxFreeCardsReached:
        "Vous avez déjà atteint le maximum de 10 cartes libres !",
      searchLabel: "Rechercher une carte",
      searchPlaceholder: "Rechercher...",
      clearSearch: "Effacer la recherche",
      noResults: "Aucune carte ne correspond à votre recherche.",
      clearSelection: "Effacer la sélection",
      selectedCount: "{count} carte(s) sélectionnée(s)",
      tapToSelectHelp:
        "Touchez les cartes à ajouter, puis envoyez-les plateau pour les placer.",
      goToBoard: "Envoyer au plateau ({count})",
    },
    addCardModal: {
      title: "À vous de jouer !",
      placeholder: "Entrez votre texte (max. 50 caractères)",
      emptyError: "Veuillez entrer un texte pour la carte.",
      validate: "Valider",
      close: "Fermer",
      customCards: "cartes personnalisées",
      colorLabel: "Couleur de la bordure :",
      colorCategories: {
        lime: "Carte libre",
        pink: "Domaines artistiques",
        purple: "Conditions & recommandations équipe",
        turquoise: "Visées & effets",
        orange: "Conditions & recommandations enseignant",
      },
    },
    gdprPage: {
      title: "RGPD & Confidentialité",
      intro:
        "La Ruche est un outil pédagogique développé par des équipes universitaires belges dans le cadre du Pacte pour un Enseignement d'excellence. Cette page explique comment vos données sont collectées, utilisées et protégées.",
      section1Title: "1. Données collectées",
      section1:
        "Lors de votre inscription, La Ruche collecte : votre nom d'utilisateur, votre adresse e-mail, votre prénom, votre nom de famille et votre rôle dans l'enseignement. Ces informations sont nécessaires pour vous identifier et personnaliser votre expérience.",
      section2Title: "2. Utilisation des données",
      section2:
        "Vos données sont utilisées exclusivement dans le cadre du fonctionnement de La Ruche : authentification, gestion de vos ruches pédagogiques, invitations à collaborer et correspondance par e-mail (ex. : réinitialisation de mot de passe). Elles ne sont jamais vendues ni transmises à des tiers à des fins commerciales.",
      section3Title: "3. Conservation des données",
      section3:
        "Vos données sont conservées tant que votre compte est actif. Vous pouvez supprimer votre compte à tout moment depuis votre profil, ce qui entraîne la suppression définitive de toutes les données associées.",
      section4Title: "4. Sécurité",
      section4:
        "Les mots de passe sont cryptés avant d'être stockés. Les communications entre votre navigateur et le serveur sont chiffrées via HTTPS. Aucun mot de passe n'est conservé en clair.",
      section5Title: "5. Vos droits",
      section5a:
        "Conformément au Règlement Général sur la Protection des Données (",
      section5Link: "RGPD, UE 2016/679",
      section5b:
        "), vous disposez d'un droit d'accès, de rectification, de suppression et de portabilité de vos données. Pour exercer ces droits, contactez-nous via le site PECA.",
      section6Title: "6. Cookies",
      section6:
        "La Ruche n'utilise pas de cookies de traçage ou publicitaires. Un jeton d'authentification JWT est stocké localement dans votre navigateur pour maintenir votre session active.",
      contact:
        "Pour toute question relative à la confidentialité, contactez l'équipe PECA via",
      contactLinkLabel: "peca.be",
    },
    wipPage: {
      title: "Historique & à venir",
      intro:
        "La Ruche est un projet vivant. Cette page retrace son évolution et présente les fonctionnalités prévues.",
      historyTitle: "Historique des versions",
      v1Title: "V1 — Prototype frontend (2025)",
      v1Body:
        "La première version de La Ruche était une application purement frontend (interface client) : aucun compte, aucune sauvegarde serveur. Les utilisateurs construisaient leur plateau de cartes en local dans le navigateur, avec possibilité d’export PNG. Simple, rapide, mais sans persistance ni collaboration.",
      v2Title: "V2 — Plateforme collaborative (2025–aujourd’hui)",
      v2Body:
        "La V2 introduit un back-end (serveur) complet : comptes utilisateurs, sauvegarde des ruches en base de données, système de collaboration (invitations, rôles, boîte de réception), commentaires et réponses dans chaque ruche, notes de cartes, export PNG de tout le plateau (avant et arrière des cartes, commentaires et messages dans la discussion), support trilingue (FR/EN/NL), panneau d’administration, et détection des conflits de version entre collaborateurs.",
      upcomingTitle: "À venir",
      feature1Title: "Collaboration en temps réel améliorée",
      feature1:
        "Meilleure gestion de plusieurs utilisateurs travaillant simultanément sur la même ruche : mises à jour instantanées, sans conflits de version.",
      feature2Title: "Envoi d’e-mails",
      feature2:
        "Réinitialisation de mot de passe et notifications par e-mail entièrement opérationnelles.",
      feature3Title: "Forum La Ruche",
      feature3:
        "Un espace communautaire pour signaler des bugs, suivre les mises à jour et échanger autour des usages pédagogiques.",
      status: "En cours de développement",
      back: "Retour à l’accueil",
    },
    bugReportPage: {
      title: "Signaler un bug",
      intro:
        "Si quelque chose ne fonctionne pas comme prévu, cette page vous aide à nous envoyer un message clair et utile, même sans vocabulaire technique.",
      context:
        "La Ruche est encore un site récent, développé avec beaucoup de soin mais sans prétention de niveau professionnel. Il peut donc rester quelques bugs, et vos signalements nous aident vraiment à améliorer l’outil.",
      section1Title: "1. Où le problème apparaît-il ?",
      section1:
        "Indiquez la page ou la fonctionnalité concernée. Par exemple : connexion, profil, commentaires, export PNG ou une ruche précise.",
      section2Title: "2. Que faisiez-vous juste avant ?",
      section2:
        "Décrivez les étapes dans l’ordre, avec des mots simples. Exemple : j’ai ouvert une ruche, déplacé une carte, puis cliqué sur enregistrer.",
      section3Title: "3. Qu’est-ce qui s’est passé ?",
      section3:
        "Expliquez le résultat observé : message d’erreur, écran vide, bouton bloqué, contenu disparu ou comportement inattendu.",
      section4Title: "4. Quel résultat attendiez-vous ?",
      section4:
        "Dites-nous ce qui aurait dû se passer normalement. Cela nous aide à comprendre plus vite l’écart entre attendu et réel.",
      tipsTitle: "Informations très utiles à ajouter",
      tip1: "Précisez si le problème arrive toujours, parfois, ou seulement une seule fois.",
      tip2: "Ajoutez une capture d’écran si vous pouvez, surtout s’il y a un message affiché.",
      tip3: "Indiquez l’appareil utilisé, le navigateur, et le nom de la ruche concernée si vous le connaissez.",
      sendButton: "Ouvrir un e-mail de signalement",
      emailNote:
        "Le bouton ouvre votre application e-mail avec un sujet et un modèle déjà préparés à envoyer à laruche.support@cfwb.be.",
      emailSubject: "La Ruche - Signalement de bug",
      emailTemplate:
        "Bonjour,\n\nJe souhaite signaler un bug dans La Ruche.\n\n1. Où le problème apparaît-il ?\n(Page ou fonctionnalité concernée)\n\n2. Que faisiez-vous juste avant ?\n(étapes simples, une par ligne)\n\n3. Qu’est-ce qui s’est passé ?\n(message d’erreur, blocage, résultat inattendu)\n\n4. Quel résultat attendiez-vous ?\n(résultat attendu)\n\n5. Le problème est-il reproductible ?\n(toujours / parfois / une seule fois)\n\n6. Informations utiles\n- Appareil :\n- Navigateur :\n- Nom de la ruche :\n- Capture d’écran ou fichier joint :\n\nMerci.",
    },
    tutorial: {
      title: "Tutoriel",
    },
    passwordField: {
      showPassword: "Afficher le mot de passe",
    },
  },
  en: {
    common: {
      loading: "Loading...",
      close: "Close",
      cancel: "Cancel",
      save: "Save",
      edit: "Edit",
      delete: "Delete",
      confirm: "Confirm",
      page: "Page",
      previous: "Previous",
      next: "Next",
      charactersLeft: "{count} characters left",
      unknownUser: "Unknown user",
      yes: "Yes",
      no: "No",
      unexpectedError: "An unexpected error occurred.",
    },
    apiErrors: {
      AUTH_REQUIRED: "Authentication required.",
      AUTH_INVALID_USER: "Invalid user.",
      AUTH_SESSION_INVALID: "Invalid or expired session.",
      AUTH_ADMIN_REQUIRED: "Admin access required.",
      AUTH_INVALID_CREDENTIALS: "Invalid credentials.",
      AUTH_USERNAME_TAKEN: "Username already in use.",
      AUTH_EMAIL_TAKEN: "Email already in use.",
      AUTH_INVALID_EMAIL: "Invalid email.",
      AUTH_RESET_LINK_INVALID: "Invalid or expired link.",
      VALIDATION_INVALID_DATA: "Invalid data.",
      VALIDATION_INVALID_ROLE: "Invalid role.",
      VALIDATION_ROLE_REQUIRED: "Please specify your role.",
      PASSWORDS_DO_NOT_MATCH: "Passwords do not match.",
      PROFILE_USER_NOT_FOUND: "User not found.",
      PROFILE_PASSWORD_CURRENT_INCORRECT: "Current password is incorrect.",
      PROFILE_CONFIRMATION_INVALID: "Invalid confirmation.",
      PROFILE_CONFIRM_DELETE_REQUIRED: "Please confirm with DELETE.",
      PROFILE_PASSWORD_INCORRECT: "Incorrect password.",
      PROFILE_PASSWORD_CHANGE_FIELDS_REQUIRED:
        "Please provide your current password and confirm the new password.",
      HIVE_NOT_FOUND: "Hive not found.",
      HIVE_ACCESS_DENIED: "Access denied.",
      HIVE_INVALID_DATA: "Invalid hive data.",
      HIVE_TITLE_TOO_LONG: "Hive title must be 100 characters or fewer.",
      HIVE_EDIT_FORBIDDEN: "You are not allowed to edit this hive.",
      HIVE_RENAME_FORBIDDEN: "You are not allowed to rename this hive.",
      HIVE_VERSION_INVALID: "Invalid hive version.",
      HIVE_VERSION_REQUIRED:
        "Missing hive version. Reload the hive before saving.",
      HIVE_VERSION_CONFLICT:
        "This hive was modified by another collaborator. Reload it before saving.",
      HIVE_CARD_NOTE_INVALID: "Invalid card note.",
      HIVE_CARD_NOTE_FORBIDDEN:
        "You are not allowed to add notes on this hive.",
      HIVE_CARD_NOTE_CARD_NOT_FOUND: "This card was not found in the hive.",
      HIVE_COMMENT_INVALID: "Invalid comment.",
      HIVE_COMMENT_FORBIDDEN: "You are not allowed to comment on this hive.",
      HIVE_COMMENT_PARENT_NOT_FOUND: "Parent comment not found.",
      HIVE_COMMENT_NOT_FOUND: "Comment not found.",
      HIVE_COMMENT_LIMIT_REACHED:
        "The maximum number of comments has been reached for this hive.",
      HIVE_COMMENT_RATE_LIMIT:
        "You are commenting too quickly. Please try again in a moment.",
      HIVE_COMMENT_EDIT_OWN_ONLY: "You can only edit your own comments.",
      HIVE_COMMENT_DELETE_OWN_ONLY: "You can only delete your own comments.",
    },
    apiMessages: {
      MSG_PASSWORD_RESET_EMAIL_SENT:
        "If the account exists, an email has been sent.",
      MSG_PASSWORD_UPDATED: "Password updated.",
      MSG_PROFILE_UPDATED: "Profile updated.",
      MSG_PROFILE_DELETED: "Profile deleted.",
    },
    language: {
      label: "Language",
      fr: "Français",
      en: "English",
      nl: "Nederlands",
    },
    header: {
      profile: "Profile",
      inbox: "Inbox",
      admin: "Admin",
      logout: "Log out",
      login: "Log in",
      register: "Create account",
      hiveMenu: "Hive menu",
      accountMenu: "Account",
    },
    landing: {
      title: "Welcome to La Ruche",
      loading: "Loading your session...",
      connected: "Continue your work in just a few clicks.",
      guest: "Log in or create your account to get started.",
      goProfile: "Go to profile",
      createHive: "Create a Hive",
      learnMore: "Learn more",
      signIn: "Log in",
      createAccount: "Create account",
      tutorial: "Tutorial",
      tutorialPlaceholder: "Complete guide and video tutorial",
      gdpr: "GDPR / Privacy",
      gdprPlaceholder: "Data, cookies, GDPR rights — read our privacy policy.",
      reportBug: "Report a bug",
      wip: "Work in Progress",
      wipPlaceholder: "V1, V2, upcoming features — discover the roadmap.",
      contact: "Contact",
    },
    login: {
      title: "Log in",
      identifier: "Username or email",
      password: "Password",
      submit: "Log in",
      submitting: "Logging in...",
      forgot: "Forgot password?",
      noAccount: "No account yet?",
      register: "Sign up",
    },
    register: {
      charactersLeft: "{count} tekens over",
      title: "Create account",
      requiredNotice: "All fields are mandatory.",
      username: "Username (unique)",
      email: "Email",
      firstName: "First name",
      lastName: "Last name",
      role: "Role",
      roleOther: "Specify your role",
      password: "Password",
      passwordConfirm: "Confirm password",
      submit: "Create my account",
      submitting: "Creating...",
    },
    forgotPassword: {
      title: "Forgot password",
      email: "Email",
      submit: "Send link",
      submitting: "Sending...",
    },
    resetPassword: {
      invalidLink: "Invalid link",
      title: "New password",
      password: "Password",
      passwordConfirm: "Confirm password",
      submit: "Update",
      submitting: "Updating...",
    },
    protectedRoute: { loading: "Loading..." },
    profile: {
      title: "My profile",
      hivesTab: "My hives",
      settingsTab: "Edit profile",
      username: "Username",
      email: "Email",
      firstname: "First name",
      lastname: "Last name",
      role: "Role",
      createNewHive: "Create a new Hive",
      modalselectHiveTypeTitle: "Hive type",
      selectHiveTypeMessage: "What type of hive do you want to create?",
      selectStandardHive: "Standard hive",
      selectDcoHive: "DCO hive",
      myHives: "My Hives",
      sharedHives: "Shared Hives",
      createdAt: "Created on",
      updatedAt: "Last edited",
      open: "Open",
      renameHive: "Rename hive",
      duplicate: "Duplicate",
      duplicating: "Duplicating...",
      renaming: "Renaming...",
      deleteProfileTitle: "Delete my profile",
      deleteProfileDesc:
        "This action is irreversible and will delete your data.",
      confirmDeletion: "Confirm deletion",
      enterPasswords: "Enter your password twice to delete the account.",
      confirmPassword: "Confirm password",
      show: "Show",
      hide: "Hide",
      deleting: "Deleting...",
      loadingTitle: "Loading profile",
      loadingSubtitle: "We are retrieving your information and hives.",
      modalDeleteHiveTitle: "Delete hive",
      modalDeleteHiveMessage:
        "This action is irreversible. Do you want to continue?",
      modalDuplicateTitle: "Duplicate hive",
      modalDuplicateMessage: "Choose a new name for the copy.",
      modalDuplicateInput: "Copy name",
      modalDuplicateConfirm: "Create copy",
      modalCreateTitle: "Create a new hive",
      modalCreateMessage: "Choose a name for your new hive.",
      modalCreateInput: "Hive name",
      modalCreatePlaceholder:
        "Example: Theatre project hive P2 Fox School 2024",
      missingPasswordFields: "Please fill in both password fields.",
      passwordMismatch: "Passwords do not match.",
      duplicateNeedTitle: "Please provide a title for the copy.",
      duplicateRenameRequired: "Rename the copy with a different title.",
      copySuffix: "copy",
      emptyHive: "empty hive",
      download: "Download",
      downloading: "Downloading...",
      downloadFailed: "Download failed: {message}",
      searchLabel: "Search a hive",
      searchPlaceholder: "Hive name...",
      clearSearch: "Clear search",
      sortLabel: "Sort by",
      filterLabel: "Filter",
      filterAll: "All hives",
      sortDateDesc: "Date (most recent)",
      sortDateAsc: "Date (oldest)",
      sortNameAsc: "Name (A-Z)",
      sortNameDesc: "Name (Z-A)",
      noSearchResults: "No hives match your search.",
      modifyProfileTitle: "Edit my profile",
      modifyProfileDesc: "Update your role or password.",
      changeRole: "Change role",
      changePassword: "Change password",
      updateRole: "Update role",
      updatingRole: "Updating role...",
      updatePassword: "Update password",
      updatingPassword: "Updating password...",
      currentPassword: "Current password",
      newPassword: "New password",
      newPasswordConfirm: "Confirm new password",
      updateSuccess: "Profile updated successfully.",
      passwordUpdateSuccess: "Password updated successfully.",
      roleRequired: "Please select a role.",
      roleOtherRequired: "Please specify your role.",
      passwordUpdateRequiredFields:
        "Please complete all three password fields.",
      passwordTooShort: "The new password must be at least 8 characters long.",
    },
    inbox: {
      title: "Invitations",
      subtitle: "Accept or decline collaboration requests.",
      loading: "Loading invitations...",
      empty: "No pending invitations.",
      invitedBy: "Invited by",
      role: "Role",
      sentAt: "Sent on",
      accept: "Accept",
      accepting: "Accepting...",
      decline: "Decline",
      declining: "Declining...",
      unknownHive: "Unknown hive",
      loadError: "Unable to load invitations.",
      actionError: "Unable to process this invitation.",
    },
    admin: {
      title: "Administration",
      users: "Users",
      hives: "Hives",
      searchUsers: "Search (name, email, role)...",
      searchHives: "Search (title, owner)...",
      user: "User",
      role: "Role",
      hiveCount: "Hives",
      collabs: "Collabs",
      comments: "Comments",
      createdAt: "Created on",
      updatedAt: "Last edited",
      lastActivityAt: "Last activity",
      actions: "Actions",
      edit: "Edit",
      cancelEdit: "Cancel",
      save: "Save",
      owner: "Owner",
      titleLabel: "Title",
      specify: "Specify",
      deleteUser: "Delete user",
      deleteHive: "Delete hive",
      irreversible: "This action is irreversible. Continue?",
      confirmDeleteFinal: "Final confirmation",
      doubleConfirmMessage:
        "Are you absolutely sure you want to delete this item?",
      viewHive: "View",
      hiveDetails: "Hive details",
      hiveCollaborators: "Collaborators",
      hiveComments: "Comments",
      noCollaborators: "No collaborators.",
      noComments: "No comments.",
      removeCollaborator: "Remove",
      confirmRemoveCollaborator: "Remove collaborator?",
      confirmRemoveMessage:
        "Do you want to remove this collaborator from the hive?",
      confirmDeleteComment: "Delete this comment?",
      deleting: "Deleting...",
      removingCollaborator: "Removing...",
      deletingComment: "Deleting comment...",
    },
    editor: {
      newHiveTitle: "New Hive",
      newDcoHiveTitle: "New DCO Hive",
      backToProfile: "My hives",
      hiveTitleLabel: "Hive title",
      saveHive: "Save hive",
      saving: "Saving...",
      duplicateInfo: "This hive is a copy. Rename it before saving.",
      createdAt: "Created on",
      updatedAt: "Last edited",
      updating: "Updating...",
      loadingTitle: "Loading hive",
      loadingSubtitle: "Cards and comments are loading.",
      commentsTitle: "Hive chat",
      noComments: "No comments yet.",
      reply: "Reply",
      edit: "Edit",
      delete: "Delete",
      replyPlaceholder: "Write a reply...",
      send: "Send",
      sending: "Sending...",
      addCommentPlaceholder: "Add a comment...",
      loadOlderComments: "Load older comments",
      loadingOlderComments: "Loading older comments...",
      commentsMaxReached: "Maximum number of comments reached for this hive.",
      unsavedTitle: "Unsaved changes",
      unsavedMessage: "Your hive has unsaved changes. Leave without saving?",
      saveFirstTitle: "Save the hive first",
      saveFirstMessage: "Please save your hive to access {feature}.",
      stay: "Stay",
      saveAndLeave: "Save and leave",
      leaveWithoutSaving: "Leave without saving",
      editCommentTitle: "Edit comment",
      newMessage: "New message",
      deleteCommentTitle: "Delete comment",
      updatingComment: "Updating comment...",
      deletingComment: "Deleting comment...",
      saveTitleError: "Please provide a title before saving.",
      duplicateRenameError: "Rename the copy before saving.",
      saveStatusSaving: "Saving hive...",
      saveStatusSaved: "Hive saved.",
      saveStatusError: "Save failed.",
      renameOrDuplicateTitle: "Rename or create a copy?",
      renameOrDuplicateMessage:
        "Do you want to rename the existing hive '{oldTitle}' to '{newTitle}' or create a copy with this new title?",
      renameOnly: "Rename",
      createCopy: "Create a copy",
      duplicateSuccess:
        "Copy created successfully! The hive '{newTitle}' has been created and you can find it in your profile.",
      conflictTitle: "Concurrent update detected",
      conflictMessage:
        "Another collaborator saved this hive before you. Reload the latest version or create a copy to keep your work.",
      conflictReload: "Reload latest",
      activeEditorsOthers: "Currently editing: {names}",
      activeEditorsOnlyYou: "You are currently editing this hive.",
    },
    workspace: {
      cardNoteTitle: "Card note",
      editNotAllowed: "You cannot edit this hive.",
      showLibrary: "Show library",
      hideLibrary: "Hide library",
      closeLibrary: "Close library",
      enableMultiSelect: "Multi-select",
      disableMultiSelect: "Done selecting",
      returnSelectedToLibrary: "Return to library ({count})",
      returnSingleSelectedToLibrary: "Return card to library",
      selectAll: "Select all",
      tabletSelectHint: "Tap a card to select it",
      zoomOut: "-",
      zoomIn: "+",
      resetZoom: "100%",
      fitContent: "Fit cards",
      fitBoard: "Overview",
      undo: "Undo",
      redo: "Redo",
      cardLabel: "Card",
      createdBy: "Created on {date} by {user}",
      updatedBy: "Last edited on {date} by {user}",
      noCardNote: "No note for this card.",
      cardNoteReadOnlyHint: "You can view this note, but you cannot edit it.",
      cardNoteSaveFirst: "Save your hive to access card notes.",
      addCardNotePlaceholder: "Add a note to this card...",
      editCardNotePlaceholder: "Edit this card note...",
      add: "Add",
      continueDeleteCardNotes: "Continue",
      deleteCardNotesTitle: "Delete card notes",
      deleteSingleCardNoteMessage:
        "This card contains a note. Returning it to the library will delete that note. Continue?",
      deleteMultipleCardNoteMessage:
        "Some cards contain notes. Returning them to the library will delete those notes. Continue?",
      deleteCardNoteTitle: "Delete card note",
      deletingCardNote: "Deleting note...",
      irreversible: "This action is irreversible. Continue?",
      historyLimitReached:
        "History limit reached ({count} actions). The oldest actions are discarded.",
      tabletOnlyMessage:
        "The editor is optimized for desktop and tablet landscape mode. Switch to landscape on a tablet to continue.",
    },
    toolbar: {
      reset: "Reset",
      confirmResetTitle: "Reset hive",
      confirmResetMessage:
        "Are you sure you want to reset the hive? This will remove all cards from the board.",
      confirmReset: "Reset",
      export: "Export",
      exporting: "Exporting...",
      collaborators: "Collaborators",
      comments: "Comments",
      manageCollaborators: "Manage collaborators",
      invite: "Invite",
      inviting: "Inviting...",
      currentCollaborators: "Current collaborators",
      noCollaborators: "No collaborators yet.",
      remove: "Remove",
      leaveHive: "Leave hive",
      leaving: "Leaving...",
      confirmLeaveTitle: "Leave hive",
      confirmLeaveMessage: "Do you really want to leave this hive?",
      confirmLeave: "Leave",
      exportTitle: "Hive export",
      roleAdmin: "Administrator",
      roleEdit: "Collaborator (can edit)",
      roleComment: "Comment only",
      roleRead: "Read only",
      inviteRequiredEmail: "Cannot send invitation: email is required.",
      inviteInvalidEmail: "Cannot send invitation: please enter a valid email.",
      inviteUnavailable: "Invitation is currently unavailable.",
      inviteNoUser:
        "Invitation failed: no user exists with this email. The collaborator must create an account first.",
      inviteInvalid: "Invalid invitation: check the email and try again.",
      inviteSent: "Invitation sent.",
      invitesLoadFailed: "Unable to load sent invitations.",
      sentInvitations: "Sent invitations",
      noSentInvitations: "No invitations sent yet.",
      inviteStatusPending: "Pending",
      inviteStatusAccepted: "Accepted",
      inviteStatusDeclined: "Declined",
      inviteFailed: "Invitation failed.",
      invalidRole: "Invalid role",
      removeFailed: "Cannot remove this collaborator",
      leaveFailed: "Cannot leave this hive",
      exportFailed: "Export failed: {message}",
      exportMergeError: "Unable to generate merged export.",
      frontBoardExportName: "front-board",
      backBoardExportName: "back-board",
      chatExportName: "hive-chat",
      cardNotesExportName: "card-notes",
      cardNotesExportTitle: "Card notes",
      noCardNotesExport: "No board card has a note.",
    },
    cardLibrary: {
      title: "Available cards",
      remaining: "remaining",
      freeCardTitle: "Your turn!",
      editNotAllowed: "You cannot edit this hive.",
      maxFreeCardsReached: "You already reached the maximum of 10 free cards!",
      searchLabel: "Search a card",
      searchPlaceholder: "Search...",
      clearSearch: "Clear search",
      noResults: "No cards match your search.",
      clearSelection: "Clear selection",
      selectedCount: "{count} card(s) selected",
      tapToSelectHelp:
        "Tap cards to add them, then send them to the board to place them.",
      goToBoard: "Go to board ({count})",
    },
    addCardModal: {
      title: "Your turn!",
      placeholder: "Enter your text (max. 50 characters)",
      emptyError: "Please enter text for the card.",
      validate: "Validate",
      close: "Close",
      customCards: "custom cards",
      colorLabel: "Border color:",
      colorCategories: {
        lime: "Free card",
        pink: "Artistic domains",
        purple: "Team conditions & recommendations",
        turquoise: "Aims & impacts",
        orange: "Teacher conditions & recommendations",
      },
    },
    gdprPage: {
      title: "GDPR & Privacy",
      intro:
        "La Ruche is an educational tool developed by Belgian university teams as part of the Pact for Excellence in Education. This page explains how your data is collected, used, and protected.",
      section1Title: "1. Data collected",
      section1:
        "When you register, La Ruche collects: your username, email address, first name, last name, and your role in education. This information is necessary to identify you and personalise your experience.",
      section2Title: "2. Use of data",
      section2:
        "Your data is used exclusively for the operation of La Ruche: authentication, management of your pedagogical hives, collaboration invitations, and email correspondence (e.g. password reset). It is never sold or shared with third parties for commercial purposes.",
      section3Title: "3. Data retention",
      section3:
        "Your data is retained for as long as your account is active. You can delete your account at any time from your profile, which permanently removes all associated data.",
      section4Title: "4. Security",
      section4:
        "Passwords are hashed and salted before storage. Communications between your browser and the server are encrypted via HTTPS. No password is ever stored in plain text.",
      section5Title: "5. Your rights",
      section5a: "Under the General Data Protection Regulation (",
      section5Link: "GDPR, EU 2016/679",
      section5b:
        "), you have the right to access, rectify, delete, and export your data. To exercise these rights, contact us via the PECA project website.",
      section6Title: "6. Cookies",
      section6:
        "La Ruche does not use tracking or advertising cookies. A JWT authentication token is stored locally in your browser to maintain your active session.",
      contact: "For any privacy-related question, contact the PECA team via",
      contactLinkLabel: "peca.be",
    },
    wipPage: {
      title: "History & Coming Soon",
      intro:
        "La Ruche is a living project. This page retraces its evolution and presents the features planned next.",
      historyTitle: "Version history",
      v1Title: "V1 - Frontend prototype (2025)",
      v1Body:
        "The first version of La Ruche was a frontend-only application: no accounts and no server-side persistence. Users built their card board locally in the browser, with PNG export available. Simple and fast, but without persistence or collaboration.",
      v2Title: "V2 - Collaborative platform (2025-present)",
      v2Body:
        "V2 introduced a complete back-end: user accounts, database persistence for hives, a collaboration system (invitations, roles, inbox), comments and replies in each hive, card notes, PNG export of the full board (front and back of cards, comments, and discussion messages), trilingual support (FR/EN/NL), an administration panel, and version conflict detection between collaborators.",
      upcomingTitle: "Coming soon",
      feature1Title: "Improved real-time collaboration",
      feature1:
        "We are working to improve the management of multiple users working simultaneously on the same hive. The goal is to make updates instant and seamless, prevent version conflicts, and allow each collaborator to see others\u2019 changes in real time.",
      feature2Title: "Email delivery",
      feature2:
        "Password reset emails and email notifications are fully operational.",
      feature3Title: "La Ruche Forum",
      feature3:
        "A community space is being created to allow La Ruche users to report bugs, follow updates, suggest improvements, and share pedagogical practices around the tool.",
      status: "Status: In development",
      back: "Back to home",
    },
    bugReportPage: {
      title: "Report a bug",
      intro:
        "If something does not work as expected, this page helps you send us a clear and useful report, even if you are not used to technical terms.",
      context:
        "La Ruche is still a new website, built with care but not by a professional developer. Some bugs may still remain, and your reports genuinely help improve the tool.",
      section1Title: "1. Where does the problem happen?",
      section1:
        "Tell us which page or feature is concerned. For example: login, profile, comments, PNG export, or a specific hive.",
      section2Title: "2. What were you doing just before?",
      section2:
        "Describe the steps in order, using simple words. Example: I opened a hive, moved a card, then clicked save.",
      section3Title: "3. What happened?",
      section3:
        "Explain what you saw: an error message, a blank screen, a blocked button, missing content, or any unexpected behaviour.",
      section4Title: "4. What should have happened instead?",
      section4:
        "Tell us what you expected to happen. This helps us understand the difference between the expected result and the actual one.",
      tipsTitle: "Very helpful details to include",
      tip1: "Tell us whether the issue happens every time, sometimes, or only once.",
      tip2: "Add a screenshot if you can, especially if a message is displayed.",
      tip3: "Include the device, browser, and hive name if you know them.",
      sendButton: "Open a bug report email",
      emailNote:
        "The button opens your email app with a prepared subject and message template addressed to laruche.support@cfwb.be.",
      emailSubject: "La Ruche - Bug report",
      emailTemplate:
        "Hello,\n\nI would like to report a bug in La Ruche.\n\n1. Where does the problem happen?\n(page or feature concerned)\n\n2. What were you doing just before?\n(simple steps, one per line)\n\n3. What happened?\n(error message, block, unexpected result)\n\n4. What should have happened instead?\n(expected result)\n\n5. Can you reproduce the problem?\n(always / sometimes / only once)\n\n6. Useful information\n- Device:\n- Browser:\n- Hive name:\n- Screenshot or attached file:\n\nThank you.",
    },
    tutorial: {
      title: "Tutorial",
    },
    passwordField: { showPassword: "Show password" },
  },
  nl: {
    common: {
      loading: "Laden...",
      close: "Sluiten",
      cancel: "Annuleren",
      save: "Opslaan",
      edit: "Bewerken",
      delete: "Verwijderen",
      confirm: "Bevestigen",
      page: "Pagina",
      previous: "Vorige",
      next: "Volgende",
      charactersLeft: "{count} tekens over",
      unknownUser: "Onbekende gebruiker",
      yes: "Ja",
      no: "Nee",
      unexpectedError: "Er is een onverwachte fout opgetreden.",
    },
    apiErrors: {
      AUTH_REQUIRED: "Authenticatie vereist.",
      AUTH_INVALID_USER: "Ongeldige gebruiker.",
      AUTH_SESSION_INVALID: "Sessie ongeldig of verlopen.",
      AUTH_ADMIN_REQUIRED: "Beheerdersrechten vereist.",
      AUTH_INVALID_CREDENTIALS: "Ongeldige inloggegevens.",
      AUTH_USERNAME_TAKEN: "Gebruikersnaam is al in gebruik.",
      AUTH_EMAIL_TAKEN: "E-mail is al in gebruik.",
      AUTH_INVALID_EMAIL: "Ongeldig e-mailadres.",
      AUTH_RESET_LINK_INVALID: "Ongeldige of verlopen link.",
      VALIDATION_INVALID_DATA: "Ongeldige gegevens.",
      VALIDATION_INVALID_ROLE: "Ongeldige rol.",
      VALIDATION_ROLE_REQUIRED: "Specificeer je rol.",
      PASSWORDS_DO_NOT_MATCH: "Wachtwoorden komen niet overeen.",
      PROFILE_USER_NOT_FOUND: "Gebruiker niet gevonden.",
      PROFILE_PASSWORD_CURRENT_INCORRECT: "Huidig wachtwoord is onjuist.",
      PROFILE_CONFIRMATION_INVALID: "Ongeldige bevestiging.",
      PROFILE_CONFIRM_DELETE_REQUIRED: "Bevestig met DELETE.",
      PROFILE_PASSWORD_INCORRECT: "Onjuist wachtwoord.",
      PROFILE_PASSWORD_CHANGE_FIELDS_REQUIRED:
        "Vul je huidige wachtwoord in en bevestig het nieuwe wachtwoord.",
      HIVE_NOT_FOUND: "Bijenkorf niet gevonden.",
      HIVE_ACCESS_DENIED: "Toegang geweigerd.",
      HIVE_INVALID_DATA: "Ongeldige bijenkorfgegevens.",
      HIVE_TITLE_TOO_LONG:
        "De titel van de bijenkorf mag maximaal 100 tekens bevatten.",
      HIVE_EDIT_FORBIDDEN: "Je mag deze bijenkorf niet bewerken.",
      HIVE_RENAME_FORBIDDEN: "Je mag deze bijenkorf niet hernoemen.",
      HIVE_VERSION_INVALID: "Ongeldige bijenkorfversie.",
      HIVE_VERSION_REQUIRED:
        "Ontbrekende bijenkorfversie. Herlaad de bijenkorf voor je opslaat.",
      HIVE_VERSION_CONFLICT:
        "Deze bijenkorf is aangepast door een andere medewerker. Herlaad voor je opslaat.",
      HIVE_CARD_NOTE_INVALID: "Ongeldige kaartnotitie.",
      HIVE_CARD_NOTE_FORBIDDEN:
        "Je mag geen notities toevoegen aan deze bijenkorf.",
      HIVE_CARD_NOTE_CARD_NOT_FOUND:
        "Deze kaart werd niet gevonden in de bijenkorf.",
      HIVE_COMMENT_INVALID: "Ongeldige opmerking.",
      HIVE_COMMENT_FORBIDDEN: "Je mag niet reageren in deze bijenkorf.",
      HIVE_COMMENT_PARENT_NOT_FOUND: "Bovenliggende opmerking niet gevonden.",
      HIVE_COMMENT_NOT_FOUND: "Opmerking niet gevonden.",
      HIVE_COMMENT_LIMIT_REACHED:
        "Het maximumaantal opmerkingen voor deze bijenkorf is bereikt.",
      HIVE_COMMENT_RATE_LIMIT:
        "Je reageert te snel. Probeer het over een ogenblik opnieuw.",
      HIVE_COMMENT_EDIT_OWN_ONLY:
        "Je kunt alleen je eigen opmerkingen bewerken.",
      HIVE_COMMENT_DELETE_OWN_ONLY:
        "Je kunt alleen je eigen opmerkingen verwijderen.",
    },
    apiMessages: {
      MSG_PASSWORD_RESET_EMAIL_SENT:
        "Als het account bestaat, is er een e-mail verzonden.",
      MSG_PASSWORD_UPDATED: "Wachtwoord bijgewerkt.",
      MSG_PROFILE_UPDATED: "Profiel bijgewerkt.",
      MSG_PROFILE_DELETED: "Profiel verwijderd.",
    },
    language: {
      label: "Taal",
      fr: "Français",
      en: "English",
      nl: "Nederlands",
    },
    header: {
      profile: "Profiel",
      inbox: "Inbox",
      admin: "Admin",
      logout: "Afmelden",
      login: "Aanmelden",
      register: "Account aanmaken",
      hiveMenu: "Bijenkorfmenu",
      accountMenu: "Account",
    },
    landing: {
      title: "Welkom bij La Ruche",
      loading: "Je sessie wordt geladen...",
      connected: "Ga verder met je werk in enkele klikken.",
      guest: "Meld je aan of maak een account om te starten.",
      goProfile: "Naar profiel",
      createHive: "Nieuwe bijenkorf maken",
      learnMore: "Meer informatie",
      signIn: "Aanmelden",
      createAccount: "Account aanmaken",
      tutorial: "Tutorial",
      tutorialPlaceholder: "Volledige gids en videotutorial",
      gdpr: "GDPR / Privacy",
      gdprPlaceholder:
        "Gegevens, cookies, AVG-rechten — lees ons privacybeleid.",
      reportBug: "Bug melden",
      wip: "In Ontwikkeling",
      wipPlaceholder: "V1, V2, komende functies — ontdek de routekaart.",
      contact: "Contact",
    },
    login: {
      title: "Aanmelden",
      identifier: "Gebruikersnaam of e-mail",
      password: "Wachtwoord",
      submit: "Aanmelden",
      submitting: "Bezig met aanmelden...",
      forgot: "Wachtwoord vergeten?",
      noAccount: "Nog geen account?",
      register: "Registreren",
    },
    register: {
      title: "Account aanmaken",
      requiredNotice: "Alle velden zijn verplicht.",
      username: "Gebruikersnaam (uniek)",
      email: "E-mail",
      firstName: "Voornaam",
      lastName: "Achternaam",
      role: "Rol",
      roleOther: "Specificeer je rol",
      password: "Wachtwoord",
      passwordConfirm: "Bevestig wachtwoord",
      submit: "Mijn account maken",
      submitting: "Bezig met aanmaken...",
    },
    forgotPassword: {
      title: "Wachtwoord vergeten",
      email: "E-mail",
      submit: "Link verzenden",
      submitting: "Verzenden...",
    },
    resetPassword: {
      invalidLink: "Ongeldige link",
      title: "Nieuw wachtwoord",
      password: "Wachtwoord",
      passwordConfirm: "Bevestig wachtwoord",
      submit: "Bijwerken",
      submitting: "Bijwerken...",
    },
    protectedRoute: { loading: "Laden..." },
    profile: {
      title: "Mijn profiel",
      hivesTab: "Mijn bijenkorfen",
      settingsTab: "Profiel wijzigen",
      username: "Gebruikersnaam",
      email: "E-mail",
      firstname: "Voornaam",
      lastname: "Achternaam",
      role: "Rol",
      createNewHive: "Nieuwe bijenkorf maken",
      modalselectHiveTypeTitle: "Type bijenkorf",
      selectHiveTypeMessage: "Welk type bijenkorf wil je maken?",
      selectStandardHive: "Standaard bijenkorf",
      selectDcoHive: "DCO-bijenkorf",
      myHives: "Mijn Bijenkorfen",
      sharedHives: "Gedeelde Bijenkorfen",
      createdAt: "Gemaakt op",
      updatedAt: "Laatste wijziging",
      open: "Openen",
      renameHive: "Bijenkorf hernoemen",
      duplicate: "Dupliceren",
      duplicating: "Bezig met dupliceren...",
      renaming: "Bezig met hernoemen...",
      deleteProfileTitle: "Mijn profiel verwijderen",
      deleteProfileDesc:
        "Deze actie is onomkeerbaar en verwijdert je gegevens.",
      confirmDeletion: "Verwijderen bevestigen",
      enterPasswords:
        "Voer je wachtwoord twee keer in om het account te verwijderen.",
      confirmPassword: "Wachtwoord bevestigen",
      show: "Tonen",
      hide: "Verbergen",
      deleting: "Bezig met verwijderen...",
      loadingTitle: "Profiel laden",
      loadingSubtitle: "We halen je gegevens en bijenkorfen op.",
      modalDeleteHiveTitle: "Bijenkorf verwijderen",
      modalDeleteHiveMessage: "Deze actie is onomkeerbaar. Wil je doorgaan?",
      modalDuplicateTitle: "Bijenkorf dupliceren",
      modalDuplicateMessage: "Kies een nieuwe naam voor de kopie.",
      modalDuplicateInput: "Naam van de kopie",
      modalDuplicateConfirm: "Kopie maken",
      modalCreateTitle: "Nieuwe bijenkorf maken",
      modalCreateMessage: "Kies een naam voor je nieuwe bijenkorf.",
      modalCreateInput: "Naam van de bijenkorf",
      modalCreatePlaceholder:
        "Bijv.: Bijenkorf theaterproject P2 Vossenschool 2024",
      missingPasswordFields: "Vul beide wachtwoordvelden in.",
      passwordMismatch: "Wachtwoorden komen niet overeen.",
      duplicateNeedTitle: "Geef een titel voor de kopie op.",
      duplicateRenameRequired: "Hernoem de kopie met een andere titel.",
      copySuffix: "kopie",
      emptyHive: "lege bijenkorf",
      download: "Downloaden",
      downloading: "Downloaden...",
      downloadFailed: "Download mislukt: {message}",
      searchLabel: "Zoek een bijenkorf",
      searchPlaceholder: "Naam van de bijenkorf...",
      clearSearch: "Zoekopdracht wissen",
      sortLabel: "Sorteren op",
      filterLabel: "Filter",
      filterAll: "Alle bijenkorfen",
      sortDateDesc: "Datum (meest recent)",
      sortDateAsc: "Datum (oudste)",
      sortNameAsc: "Naam (A-Z)",
      sortNameDesc: "Naam (Z-A)",
      noSearchResults: "Geen bijenkorven gevonden voor je zoekopdracht.",
      modifyProfileTitle: "Mijn profiel wijzigen",
      modifyProfileDesc: "Werk je rol of wachtwoord bij.",
      changeRole: "Rol wijzigen",
      changePassword: "Wachtwoord wijzigen",
      updateRole: "Rol bijwerken",
      updatingRole: "Rol wordt bijgewerkt...",
      updatePassword: "Wachtwoord bijwerken",
      updatingPassword: "Wachtwoord wordt bijgewerkt...",
      currentPassword: "Huidig wachtwoord",
      newPassword: "Nieuw wachtwoord",
      newPasswordConfirm: "Nieuw wachtwoord bevestigen",
      updateSuccess: "Profiel is succesvol bijgewerkt.",
      passwordUpdateSuccess: "Wachtwoord is succesvol bijgewerkt.",
      roleRequired: "Selecteer een rol.",
      roleOtherRequired: "Specificeer je rol.",
      passwordUpdateRequiredFields: "Vul alle drie de wachtwoordvelden in.",
      passwordTooShort:
        "Het nieuwe wachtwoord moet minstens 8 tekens bevatten.",
    },
    inbox: {
      title: "Uitnodigingen",
      subtitle: "Accepteer of weiger samenwerkingsverzoeken.",
      loading: "Uitnodigingen laden...",
      empty: "Geen openstaande uitnodigingen.",
      invitedBy: "Uitgenodigd door",
      role: "Rol",
      sentAt: "Verzonden op",
      accept: "Accepteren",
      accepting: "Bezig met accepteren...",
      decline: "Weigeren",
      declining: "Bezig met weigeren...",
      unknownHive: "Onbekende bijenkorf",
      loadError: "Uitnodigingen konden niet worden geladen.",
      actionError: "Deze uitnodiging kon niet worden verwerkt.",
    },
    admin: {
      title: "Beheer",
      users: "Gebruikers",
      hives: "Bijenkorfen",
      searchUsers: "Zoeken (naam, e-mail, rol)...",
      searchHives: "Zoeken (titel, eigenaar)...",
      user: "Gebruiker",
      role: "Rol",
      hiveCount: "Bijenkorfen",
      collabs: "Samenwerkingen",
      comments: "Reacties",
      createdAt: "Aangemaakt op",
      updatedAt: "Laatst bewerkt",
      lastActivityAt: "Laatste activiteit",
      actions: "Acties",
      edit: "Bewerken",
      cancelEdit: "Annuleren",
      save: "Opslaan",
      owner: "Eigenaar",
      titleLabel: "Titel",
      specify: "Specificeer",
      deleteUser: "Gebruiker verwijderen",
      deleteHive: "Bijenkorf verwijderen",
      irreversible: "Deze actie is onomkeerbaar. Wil je doorgaan?",
      confirmDeleteFinal: "Definitieve bevestiging",
      doubleConfirmMessage: "Weet je zeker dat je dit item wilt verwijderen?",
      viewHive: "Bekijken",
      hiveDetails: "Details bijenkorf",
      hiveCollaborators: "Medewerkers",
      hiveComments: "Reacties",
      noCollaborators: "Geen medewerkers.",
      noComments: "Geen reacties.",
      removeCollaborator: "Verwijderen",
      confirmRemoveCollaborator: "Medewerker verwijderen?",
      confirmRemoveMessage:
        "Wil je deze medewerker uit de bijenkorf verwijderen?",
      confirmDeleteComment: "Reactie verwijderen?",
      deleting: "Bezig met verwijderen...",
      removingCollaborator: "Bezig met verwijderen...",
      deletingComment: "Reactie verwijderen...",
    },
    editor: {
      newHiveTitle: "Nieuwe Bijenkorf",
      newDcoHiveTitle: "Nieuwe DCO-bijenkorf",
      backToProfile: "Mijn bijenkorfen",
      hiveTitleLabel: "Titel van de Bijenkorf",
      saveHive: "Bijenkorf opslaan",
      saving: "Opslaan...",
      duplicateInfo: "Deze bijenkorf is een kopie. Hernoem ze voor je opslaat.",
      createdAt: "Gemaakt op",
      updatedAt: "Laatst bewerkt",
      updating: "Bijwerken...",
      loadingTitle: "Bijenkorf laden",
      loadingSubtitle: "Kaarten en reacties worden geladen.",
      commentsTitle: "Bijenkorf-chat",
      noComments: "Nog geen reacties.",
      reply: "Antwoorden",
      edit: "Bewerken",
      delete: "Verwijderen",
      replyPlaceholder: "Schrijf een antwoord...",
      send: "Verzenden",
      sending: "Verzenden...",
      addCommentPlaceholder: "Reactie toevoegen...",
      loadOlderComments: "Oudere reacties laden",
      loadingOlderComments: "Oudere reacties laden...",
      commentsMaxReached:
        "Maximaal aantal reacties bereikt voor deze bijenkorf.",
      unsavedTitle: "Niet-opgeslagen wijzigingen",
      unsavedMessage:
        "Je bijenkorf bevat niet-opgeslagen wijzigingen. Verlaten zonder op te slaan?",
      saveFirstTitle: "Sla eerst de bijenkorf op",
      saveFirstMessage:
        "Sla je bijenkorf op om toegang te krijgen tot {feature}.",
      stay: "Blijven",
      saveAndLeave: "Opslaan en verlaten",
      leaveWithoutSaving: "Verlaten zonder opslaan",
      editCommentTitle: "Reactie bewerken",
      newMessage: "Nieuw bericht",
      deleteCommentTitle: "Reactie verwijderen",
      updatingComment: "Reactie bijwerken...",
      deletingComment: "Reactie verwijderen...",
      saveTitleError: "Vul een titel in voor je opslaat.",
      duplicateRenameError: "Hernoem de kopie voor je opslaat.",
      saveStatusSaving: "Bijenkorf wordt opgeslagen...",
      saveStatusSaved: "Bijenkorf opgeslagen.",
      saveStatusError: "Opslaan mislukt.",
      renameOrDuplicateTitle: "Hernoemen of kopie maken?",
      renameOrDuplicateMessage:
        "Wil je de bestaande bijenkorf '{oldTitle}' hernoemen naar '{newTitle}' of een kopie maken met deze nieuwe titel?",
      renameOnly: "Hernoemen",
      createCopy: "Kopie maken",
      duplicateSuccess:
        "Kopie met succes aangemaakt! De bijenkorf '{newTitle}' is aangemaakt en je kunt deze in je profiel vinden.",
      conflictTitle: "Gelijktijdige update gedetecteerd",
      conflictMessage:
        "Een andere samenwerker heeft deze bijenkorf eerder opgeslagen. Herlaad de nieuwste versie of maak een kopie om je werk te bewaren.",
      conflictReload: "Nieuwste versie herladen",
      activeEditorsOthers: "Momenteel aan het bewerken: {names}",
      activeEditorsOnlyYou: "Je bewerkt deze bijenkorf momenteel.",
    },
    workspace: {
      cardNoteTitle: "Kaartnotitie",
      editNotAllowed: "U kunt deze bijenkorf niet bewerken.",
      showLibrary: "Bibliotheek tonen",
      hideLibrary: "Bibliotheek verbergen",
      closeLibrary: "Bibliotheek sluiten",
      enableMultiSelect: "Meerde selectie",
      disableMultiSelect: "Selectie beëindigen",
      returnSelectedToLibrary: "Terug naar bibliotheek ({count})",
      returnSingleSelectedToLibrary: "Kaart terug naar bibliotheek",
      selectAll: "Alles selecteren",
      tabletSelectHint: "Tik op een kaart om te selecteren",
      zoomOut: "-",
      zoomIn: "+",
      resetZoom: "100%",
      fitContent: "Kaarten passend maken",
      fitBoard: "Overzicht",
      undo: "Ongedaan maken",
      redo: "Opnieuw",
      cardLabel: "Kaart",
      createdBy: "Aangemaakt op {date} door {user}",
      updatedBy: "Laatst bewerkt op {date} door {user}",
      noCardNote: "Geen notitie voor deze kaart.",
      cardNoteReadOnlyHint:
        "Je kunt deze notitie bekijken, maar niet bewerken.",
      cardNoteSaveFirst:
        "Sla je bijenkorf op om toegang te krijgen tot kaartnotities.",
      addCardNotePlaceholder: "Voeg een notitie toe aan deze kaart...",
      editCardNotePlaceholder: "Bewerk de notitie van deze kaart...",
      add: "Toevoegen",
      continueDeleteCardNotes: "Doorgaan",
      deleteCardNotesTitle: "Kaartnotities verwijderen",
      deleteSingleCardNoteMessage:
        "Deze kaart bevat een notitie. Terugplaatsen in de bibliotheek verwijdert die notitie. Doorgaan?",
      deleteMultipleCardNoteMessage:
        "Sommige kaarten bevatten notities. Terugplaatsen in de bibliotheek verwijdert die notities. Doorgaan?",
      deleteCardNoteTitle: "Kaartnotitie verwijderen",
      deletingCardNote: "Notitie verwijderen...",
      irreversible: "Deze actie is onomkeerbaar. Wil je doorgaan?",
      historyLimitReached:
        "Geschiedenislimiet bereikt ({count} acties). De oudste acties worden verwijderd.",
      tabletOnlyMessage:
        "De editor is geoptimaliseerd voor desktop en tablet in landschapsmodus. Draai je tablet naar landschap om verder te gaan.",
    },
    toolbar: {
      reset: "Resetten",
      confirmResetTitle: "Bijenkorf resetten",
      confirmResetMessage:
        "Weet je zeker dat je de bijenkorf wilt resetten? Dit verwijdert alle kaarten van het bord.",
      confirmReset: "Resetten",
      export: "Exporteren",
      exporting: "Bezig met exporteren...",
      collaborators: "Samenwerkers",
      comments: "Reacties",
      manageCollaborators: "Samenwerkers beheren",
      invite: "Uitnodigen",
      inviting: "Bezig met uitnodigen...",
      currentCollaborators: "Huidige samenwerkers",
      noCollaborators: "Nog geen samenwerkers.",
      remove: "Verwijderen",
      leaveHive: "Bijenkorf verlaten",
      leaving: "Bezig met verlaten...",
      confirmLeaveTitle: "Bijenkorf verlaten",
      confirmLeaveMessage: "Wil je deze bijenkorf echt verlaten?",
      confirmLeave: "Verlaten",
      exportTitle: "Bijenkorf-export",
      roleAdmin: "Beheerder",
      roleEdit: "Medewerker (kan bewerken)",
      roleComment: "Alleen reacties",
      roleRead: "Alleen lezen",
      inviteRequiredEmail:
        "Uitnodiging kan niet worden verzonden: e-mail is verplicht.",
      inviteInvalidEmail:
        "Uitnodiging kan niet worden verzonden: vul een geldig e-mailadres in.",
      inviteUnavailable: "Uitnodiging is momenteel niet beschikbaar.",
      inviteNoUser:
        "Uitnodiging mislukt: er bestaat geen gebruiker met dit e-mailadres. De samenwerker moet eerst een account aanmaken.",
      inviteInvalid:
        "Ongeldige uitnodiging: controleer het e-mailadres en probeer opnieuw.",
      inviteSent: "Uitnodiging verzonden.",
      invitesLoadFailed: "Verzonden uitnodigingen konden niet worden geladen.",
      sentInvitations: "Verzonden uitnodigingen",
      noSentInvitations: "Nog geen uitnodigingen verzonden.",
      inviteStatusPending: "In afwachting",
      inviteStatusAccepted: "Geaccepteerd",
      inviteStatusDeclined: "Geweigerd",
      inviteFailed: "Uitnodiging mislukt.",
      invalidRole: "Ongeldige rol",
      removeFailed: "Deze samenwerker kan niet worden verwijderd",
      leaveFailed: "Je kunt deze ruche niet verlaten",
      exportFailed: "Export mislukt: {message}",
      exportMergeError: "Samengevoegde export kon niet worden gemaakt.",
      frontBoardExportName: "bord-voorzijde",
      backBoardExportName: "bord-achterzijde",
      chatExportName: "bijenkorf-chat",
      cardNotesExportName: "kaartnotities",
      cardNotesExportTitle: "Kaartnotities",
      noCardNotesExport: "Geen enkele kaart op het bord heeft een notitie.",
    },
    cardLibrary: {
      title: "Beschikbare kaarten",
      remaining: "over",
      freeCardTitle: "Jij bent aan zet!",
      editNotAllowed: "U kunt deze bijenkorf niet bewerken.",
      maxFreeCardsReached:
        "Je hebt al het maximum van 10 vrije kaarten bereikt!",
      searchLabel: "Een kaart zoeken",
      searchPlaceholder: "Zoeken...",
      clearSearch: "Zoekopdracht wissen",
      noResults: "Geen kaarten komen overeen met uw zoekopdracht.",
      clearSelection: "Selectie wissen",
      selectedCount: "{count} kaart(en) geselecteerd",
      tapToSelectHelp:
        "Tik op kaarten om ze toe te voegen en stuur ze naar het bord om ze te plaatsen.",
      goToBoard: "Naar bord ({count})",
    },
    addCardModal: {
      title: "Jij bent aan zet!",
      placeholder: "Vul je tekst in (max. 50 tekens)",
      emptyError: "Vul tekst in voor de kaart.",
      validate: "Bevestigen",
      close: "Sluiten",
      customCards: "aangepaste kaarten",
      colorLabel: "Randkleur:",
      colorCategories: {
        lime: "Vrije kaart",
        pink: "Artistieke domeinen",
        purple: "Voorwaarden & aanbevelingen team",
        turquoise: "Doelen & effecten",
        orange: "Voorwaarden & aanbevelingen leerkracht",
      },
    },
    gdprPage: {
      title: "AVG & Privacy",
      intro:
        "La Ruche is een educatief hulpmiddel ontwikkeld door Belgische universiteitsteams in het kader van het Pact voor Excellentie in het Onderwijs. Deze pagina legt uit hoe uw gegevens worden verzameld, gebruikt en beschermd.",
      section1Title: "1. Verzamelde gegevens",
      section1:
        "Bij registratie verzamelt La Ruche: uw gebruikersnaam, e-mailadres, voornaam, achternaam en uw rol in het onderwijs. Deze informatie is noodzakelijk om u te identificeren en uw ervaring te personaliseren.",
      section2Title: "2. Gebruik van gegevens",
      section2:
        "Uw gegevens worden uitsluitend gebruikt voor de werking van La Ruche: authenticatie, beheer van uw pedagogische bijkorven, uitnodigingen voor samenwerking en e-mailcorrespondentie (bv. wachtwoord opnieuw instellen). Ze worden nooit verkocht of gedeeld met derden voor commerciële doeleinden.",
      section3Title: "3. Bewaartermijn",
      section3:
        "Uw gegevens worden bewaard zolang uw account actief is. U kunt uw account op elk moment verwijderen via uw profiel, waarna alle bijbehorende gegevens permanent worden verwijderd.",
      section4Title: "4. Beveiliging",
      section4:
        "Wachtwoorden worden gehasht en gesalt opgeslagen. Communicatie tussen uw browser en de server is versleuteld via HTTPS. Er wordt nooit een wachtwoord in leesbare tekst opgeslagen.",
      section5Title: "5. Uw rechten",
      section5a: "Op grond van de Algemene Verordening Gegevensbescherming (",
      section5Link: "AVG, EU 2016/679",
      section5b:
        ") hebt u het recht op inzage, rectificatie, verwijdering en overdraagbaarheid van uw gegevens. Neem contact op via de PECA-projectwebsite om deze rechten uit te oefenen.",
      section6Title: "6. Cookies",
      section6:
        "La Ruche maakt geen gebruik van tracking- of reclamecookies. Een JWT-authenticatietoken wordt lokaal in uw browser opgeslagen om uw actieve sessie te onderhouden.",
      contact:
        "Voor vragen over privacy kunt u contact opnemen met het PECA-team via",
      contactLinkLabel: "peca.be",
    },
    wipPage: {
      title: "Geschiedenis & Binnenkort",
      intro:
        "La Ruche is een levend project. Deze pagina beschrijft de evolutie en de geplande functies.",
      historyTitle: "Versiegeschiedenis",
      v1Title: "V1 — Frontend-prototype (2025)",
      v1Body:
        "De eerste versie van La Ruche was een puur frontend-applicatie: geen accounts, geen opslag op de server. Gebruikers bouwden hun kaartenplaat lokaal in de browser, met exportmogelijkheid naar PNG. Eenvoudig en snel, maar zonder persistentie of samenwerking.",
      v2Title: "V2 — Collaboratief platform (2025–heden)",
      v2Body:
        "V2 introduceert een volledige back-end: gebruikersaccounts, opslag van bijkorven in een database, een samenwerkingssysteem (uitnodigingen, rollen, inbox), opmerkingen en antwoorden in elke bijenkorf, kaartnotities, PNG-export van het volledige bord (voor- en achterkant van de kaarten, opmerkingen en berichten in de discussie), drietalige ondersteuning (FR/EN/NL), een beheerderspaneel en detectie van versieconflicten tussen medewerkers.",
      upcomingTitle: "Binnenkort",
      feature1Title: "Verbeterde realtime samenwerking",
      feature1:
        "Beter beheer van meerdere gebruikers die gelijktijdig aan dezelfde bijenkorf werken: directe updates zonder versieconflicten.",
      feature2Title: "E-mailverzending",
      feature2: "Wachtwoordherstel en e-mailmeldingen volledig operationeel.",
      feature3Title: "La Ruche Forum",
      feature3:
        "Een communityruimte om bugs te melden, updates te volgen en pedagogische praktijken uit te wisselen.",
      status: "In ontwikkeling",
      back: "Terug naar home",
    },
    bugReportPage: {
      title: "Bug melden",
      intro:
        "Als iets niet werkt zoals verwacht, helpt deze pagina u om een duidelijke en bruikbare melding te sturen, ook zonder technische termen.",
      context:
        "La Ruche is nog een recente website, met veel zorg ontwikkeld maar niet door een professionele ontwikkelaar. Daarom kunnen er nog enkele bugs aanwezig zijn, en uw meldingen helpen echt om het hulpmiddel te verbeteren.",
      section1Title: "1. Waar verschijnt het probleem?",
      section1:
        "Geef aan om welke pagina of functie het gaat. Bijvoorbeeld: aanmelden, profiel, reacties, PNG-export of een specifieke bijenkorf.",
      section2Title: "2. Wat deed u net ervoor?",
      section2:
        "Beschrijf de stappen in volgorde en in eenvoudige woorden. Bijvoorbeeld: ik opende een bijenkorf, versleepte een kaart en klikte daarna op opslaan.",
      section3Title: "3. Wat is er gebeurd?",
      section3:
        "Leg uit wat u zag: een foutmelding, een leeg scherm, een knop die niet werkt, verdwenen inhoud of ander onverwacht gedrag.",
      section4Title: "4. Wat had er moeten gebeuren?",
      section4:
        "Vertel ons wat u normaal verwachtte. Zo begrijpen we sneller het verschil tussen verwacht en werkelijk resultaat.",
      tipsTitle: "Heel nuttige extra informatie",
      tip1: "Geef aan of het probleem altijd, soms of slechts één keer voorkomt.",
      tip2: "Voeg indien mogelijk een schermafbeelding toe, vooral als er een bericht zichtbaar is.",
      tip3: "Vermeld het apparaat, de browser en de naam van de bijenkorf als u die kent.",
      sendButton: "E-mail voor bugmelding openen",
      emailNote:
        "De knop opent uw e-mailprogramma met een voorbereid onderwerp en sjabloon gericht aan laruche.support@cfwb.be.",
      emailSubject: "La Ruche - Bugmelding",
      emailTemplate:
        "Hallo,\n\nIk wil een bug in La Ruche melden.\n\n1. Waar verschijnt het probleem?\n(betreffende pagina of functie)\n\n2. Wat deed u net ervoor?\n(eenvoudige stappen, één per regel)\n\n3. Wat is er gebeurd?\n(foutmelding, blokkering, onverwacht resultaat)\n\n4. Wat had er moeten gebeuren?\n(verwacht resultaat)\n\n5. Kunt u het probleem opnieuw veroorzaken?\n(altijd / soms / slechts één keer)\n\n6. Nuttige informatie\n- Apparaat:\n- Browser:\n- Naam van de bijenkorf:\n- Schermafbeelding of bijlage:\n\nBedankt.",
    },
    tutorial: {
      title: "Handleiding",
      tutorialPlaceholder: "Volledige gids en videotutorial",
    },
    passwordField: { showPassword: "Wachtwoord tonen" },
  },
};
